from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from exdrf_qt.field_ed.fed_blob import DrfBlobEditor
    from exdrf_qt.field_ed.fed_bool import DrfBoolEditor
    from exdrf_qt.field_ed.fed_date import DrfDateEditor
    from exdrf_qt.field_ed.fed_dt import DrfDateTimeEditor
    from exdrf_qt.field_ed.fed_int import DrfIntEditor
    from exdrf_qt.field_ed.fed_m_text import DrfTextEditor
    from exdrf_qt.field_ed.fed_real import DrfRealEditor
    from exdrf_qt.field_ed.fed_s_text import DrfLineEditor
    from exdrf_qt.field_ed.fed_time import DrfTimeEditor


class Ui_MainWindow:
    """Autogenerated content.

    Attributes:
        central_widget: Central widget.
        ed_blob: Ed blob.
        ed_bool: Ed bool.
        ed_date: Ed date.
        ed_date_time: Ed date time.
        ed_int: Ed int.
        ed_multi: Ed multi.
        ed_real: Ed real.
        ed_single: Ed single.
        ed_string: Ed string.
        ed_text: Ed text.
        ed_time: Ed time.
        formLayout: The layout for the widget.
        statusbar: Statusbar.

    """

    central_widget: "QWidget"
    ed_blob: "DrfBlobEditor"
    ed_bool: "DrfBoolEditor"
    ed_date: "DrfDateEditor"
    ed_date_time: "DrfDateTimeEditor"
    ed_int: "DrfIntEditor"
    ed_multi: "QLineEdit"
    ed_real: "DrfRealEditor"
    ed_single: "QLineEdit"
    ed_string: "DrfLineEditor"
    ed_text: "DrfTextEditor"
    ed_time: "DrfTimeEditor"
    formLayout: "QFormLayout"
    lbl_blob: "QLabel"
    lbl_bool: "QLabel"
    lbl_date: "QLabel"
    lbl_date_time: "QLabel"
    lbl_int: "QLabel"
    lbl_multi: "QLabel"
    lbl_real: "QLabel"
    lbl_single: "QLabel"
    lbl_string: "QLabel"
    lbl_text: "QLabel"
    lbl_time: "QLabel"
    statusbar: "QStatusBar"

    def setup_ui(self, MainWindow):
        from exdrf_qt.field_ed.fed_blob import DrfBlobEditor
        from exdrf_qt.field_ed.fed_bool import DrfBoolEditor
        from exdrf_qt.field_ed.fed_date import DrfDateEditor
        from exdrf_qt.field_ed.fed_dt import DrfDateTimeEditor
        from exdrf_qt.field_ed.fed_int import DrfIntEditor
        from exdrf_qt.field_ed.fed_m_text import DrfTextEditor
        from exdrf_qt.field_ed.fed_real import DrfRealEditor
        from exdrf_qt.field_ed.fed_s_text import DrfLineEditor
        from exdrf_qt.field_ed.fed_time import DrfTimeEditor

        if not MainWindow.objectName():
            MainWindow.setObjectName("MainWindow")
        MainWindow.resize(239, 468)
        self.central_widget = QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.formLayout = QFormLayout(self.central_widget)
        self.formLayout.setObjectName("formLayout")
        self.lbl_bool = QLabel(self.central_widget)
        self.lbl_bool.setObjectName("lbl_bool")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.LabelRole, self.lbl_bool
        )

        self.ed_bool = DrfBoolEditor(parent=self.central_widget, ctx=self.ctx)
        self.ed_bool.setObjectName("ed_bool")
        self.ed_bool.setProperty("clearable", True)

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.FieldRole, self.ed_bool
        )

        self.lbl_date = QLabel(self.central_widget)
        self.lbl_date.setObjectName("lbl_date")

        self.formLayout.setWidget(
            2, QFormLayout.ItemRole.LabelRole, self.lbl_date
        )

        self.ed_date = DrfDateEditor(parent=self.central_widget, ctx=self.ctx)
        self.ed_date.setObjectName("ed_date")
        self.ed_date.setProperty("clearable", True)

        self.formLayout.setWidget(
            2, QFormLayout.ItemRole.FieldRole, self.ed_date
        )

        self.lbl_date_time = QLabel(self.central_widget)
        self.lbl_date_time.setObjectName("lbl_date_time")

        self.formLayout.setWidget(
            3, QFormLayout.ItemRole.LabelRole, self.lbl_date_time
        )

        self.ed_date_time = DrfDateTimeEditor(
            parent=self.central_widget, ctx=self.ctx
        )
        self.ed_date_time.setObjectName("ed_date_time")
        self.ed_date_time.setProperty("clearable", True)

        self.formLayout.setWidget(
            3, QFormLayout.ItemRole.FieldRole, self.ed_date_time
        )

        self.lbl_time = QLabel(self.central_widget)
        self.lbl_time.setObjectName("lbl_time")

        self.formLayout.setWidget(
            4, QFormLayout.ItemRole.LabelRole, self.lbl_time
        )

        self.ed_time = DrfTimeEditor(parent=self.central_widget, ctx=self.ctx)
        self.ed_time.setObjectName("ed_time")
        self.ed_time.setProperty("clearable", True)

        self.formLayout.setWidget(
            4, QFormLayout.ItemRole.FieldRole, self.ed_time
        )

        self.lbl_int = QLabel(self.central_widget)
        self.lbl_int.setObjectName("lbl_int")

        self.formLayout.setWidget(
            5, QFormLayout.ItemRole.LabelRole, self.lbl_int
        )

        self.ed_int = DrfIntEditor(parent=self.central_widget, ctx=self.ctx)
        self.ed_int.setObjectName("ed_int")
        self.ed_int.setProperty("clearable", True)

        self.formLayout.setWidget(
            5, QFormLayout.ItemRole.FieldRole, self.ed_int
        )

        self.lbl_real = QLabel(self.central_widget)
        self.lbl_real.setObjectName("lbl_real")

        self.formLayout.setWidget(
            6, QFormLayout.ItemRole.LabelRole, self.lbl_real
        )

        self.ed_real = DrfRealEditor(parent=self.central_widget, ctx=self.ctx)
        self.ed_real.setObjectName("ed_real")
        self.ed_real.setProperty("clearable", True)

        self.formLayout.setWidget(
            6, QFormLayout.ItemRole.FieldRole, self.ed_real
        )

        self.lbl_string = QLabel(self.central_widget)
        self.lbl_string.setObjectName("lbl_string")

        self.formLayout.setWidget(
            7, QFormLayout.ItemRole.LabelRole, self.lbl_string
        )

        self.ed_string = DrfLineEditor(parent=self.central_widget, ctx=self.ctx)
        self.ed_string.setObjectName("ed_string")
        self.ed_string.setProperty("clearable", True)

        self.formLayout.setWidget(
            7, QFormLayout.ItemRole.FieldRole, self.ed_string
        )

        self.lbl_text = QLabel(self.central_widget)
        self.lbl_text.setObjectName("lbl_text")
        sizePolicy = QSizePolicy(
            QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lbl_text.sizePolicy().hasHeightForWidth()
        )
        self.lbl_text.setSizePolicy(sizePolicy)

        self.formLayout.setWidget(
            8, QFormLayout.ItemRole.LabelRole, self.lbl_text
        )

        self.lbl_single = QLabel(self.central_widget)
        self.lbl_single.setObjectName("lbl_single")

        self.formLayout.setWidget(
            11, QFormLayout.ItemRole.LabelRole, self.lbl_single
        )

        self.ed_single = QLineEdit(self.central_widget)
        self.ed_single.setObjectName("ed_single")

        self.formLayout.setWidget(
            11, QFormLayout.ItemRole.FieldRole, self.ed_single
        )

        self.lbl_multi = QLabel(self.central_widget)
        self.lbl_multi.setObjectName("lbl_multi")

        self.formLayout.setWidget(
            12, QFormLayout.ItemRole.LabelRole, self.lbl_multi
        )

        self.ed_multi = QLineEdit(self.central_widget)
        self.ed_multi.setObjectName("ed_multi")

        self.formLayout.setWidget(
            12, QFormLayout.ItemRole.FieldRole, self.ed_multi
        )

        self.ed_text = DrfTextEditor(parent=self.central_widget, ctx=self.ctx)
        self.ed_text.setObjectName("ed_text")
        self.ed_text.setProperty("clearable", True)

        self.formLayout.setWidget(
            10, QFormLayout.ItemRole.SpanningRole, self.ed_text
        )

        self.lbl_blob = QLabel(self.central_widget)
        self.lbl_blob.setObjectName("lbl_blob")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_blob
        )

        self.ed_blob = DrfBlobEditor(parent=self.central_widget, ctx=self.ctx)
        self.ed_blob.setObjectName("ed_blob")
        self.ed_blob.setReadOnly(True)
        self.ed_blob.setProperty("clearable", True)

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.ed_blob
        )

        MainWindow.setCentralWidget(self.central_widget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslate_ui(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    # setupUi

    def retranslate_ui(self, MainWindow):
        MainWindow.setWindowTitle(
            QCoreApplication.translate("MainWindow", "MainWindow", None)
        )
        self.lbl_bool.setText(
            QCoreApplication.translate("MainWindow", "Boolean Editor", None)
        )
        self.ed_bool.setText("")
        self.lbl_date.setText(
            QCoreApplication.translate("MainWindow", "Date Editor", None)
        )
        self.lbl_date_time.setText(
            QCoreApplication.translate("MainWindow", "Date & Time Editor", None)
        )
        self.lbl_time.setText(
            QCoreApplication.translate("MainWindow", "Time Editor", None)
        )
        self.lbl_int.setText(
            QCoreApplication.translate("MainWindow", "Integer  Editor", None)
        )
        self.lbl_real.setText(
            QCoreApplication.translate("MainWindow", "Real Nr.  Editor", None)
        )
        self.lbl_string.setText(
            QCoreApplication.translate("MainWindow", "String Editor", None)
        )
        self.lbl_text.setText(
            QCoreApplication.translate("MainWindow", "Text Editor", None)
        )
        self.lbl_single.setText(
            QCoreApplication.translate("MainWindow", "Single Selector", None)
        )
        self.lbl_multi.setText(
            QCoreApplication.translate("MainWindow", "Multiple Selector", None)
        )
        self.lbl_blob.setText(
            QCoreApplication.translate("MainWindow", "Blob Editor", None)
        )

    # retranslate_ui

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.central_widget,
            self.ed_blob,
            self.ed_bool,
            self.ed_date,
            self.ed_date_time,
            self.ed_int,
            self.ed_multi,
            self.ed_real,
            self.ed_single,
            self.ed_string,
            self.ed_text,
            self.ed_time,
            self.statusbar,
        ]
