from typing import Any

from PyQt6 import QtCore, QtWidgets


class Ui_ChecksManager:
    """Autogenerated content.

    Attributes:
        c_add: C add.
        c_available: C available.
        c_available_filter: C available filter.
        c_cancel_button: C cancel button.
        c_checks_tab: C checks tab.
        c_main_button: C main button.
        c_progress: C progress.
        c_remove: C remove.
        c_result_details: C result details.
        c_results: C results.
        c_results_filter: C results filter.
        c_results_tab: C results tab.
        c_selected: C selected.
        c_stacked: C stacked.
        c_type_filter: C type filter.
        horizontalLayout: The layout for the widget.
        horizontalLayout_2: The layout for the widget.
        lay_button_box: Lay button box.
        lay_tab: Lay tab.
        page_checks: Page checks.
        page_results: Page results.
        page_results_left: Page results left.
        page_results_right: Page results right.
        splitter: Splitter.
        verticalLayout: The layout for the widget.
        verticalLayout_2: The layout for the widget.
        verticalLayout_3: The layout for the widget.
        verticalLayout_4: The layout for the widget.
        verticalLayout_5: The layout for the widget.
        verticalLayout_6: The layout for the widget.
        verticalLayout_7: The layout for the widget.

    """

    c_add: "QtWidgets.QPushButton"
    c_available: "QtWidgets.QTreeView"
    c_available_filter: "QtWidgets.QLineEdit"
    c_cancel_button: "QtWidgets.QPushButton"
    c_checks_tab: "QtWidgets.QPushButton"
    c_main_button: "QtWidgets.QPushButton"
    c_progress: "QtWidgets.QProgressBar"
    c_remove: "QtWidgets.QPushButton"
    c_result_details: "QtWidgets.QTextBrowser"
    c_results: "QtWidgets.QTreeView"
    c_results_filter: "QtWidgets.QLineEdit"
    c_results_tab: "QtWidgets.QPushButton"
    c_selected: "QtWidgets.QTreeView"
    c_stacked: "QtWidgets.QStackedWidget"
    c_type_filter: "QtWidgets.QToolButton"
    horizontalLayout: "QtWidgets.QHBoxLayout"
    horizontalLayout_2: "QtWidgets.QHBoxLayout"
    l_available: "QtWidgets.QLabel"
    l_details: "QtWidgets.QLabel"
    l_items: "QtWidgets.QLabel"
    l_selected: "QtWidgets.QLabel"
    lay_button_box: "QtWidgets.QHBoxLayout"
    lay_tab: "QtWidgets.QHBoxLayout"
    page_checks: "QtWidgets.QWidget"
    page_results: "QtWidgets.QWidget"
    page_results_left: "QtWidgets.QWidget"
    page_results_right: "QtWidgets.QWidget"
    splitter: "QtWidgets.QSplitter"
    verticalLayout: "QtWidgets.QVBoxLayout"
    verticalLayout_2: "QtWidgets.QVBoxLayout"
    verticalLayout_3: "QtWidgets.QVBoxLayout"
    verticalLayout_4: "QtWidgets.QVBoxLayout"
    verticalLayout_5: "QtWidgets.QVBoxLayout"
    verticalLayout_6: "QtWidgets.QVBoxLayout"
    verticalLayout_7: "QtWidgets.QVBoxLayout"
    ctx: "Any"  # Injected by host widget when used as mixin

    def setup_ui(self, ChecksManager):

        ChecksManager.setObjectName("ChecksManager")
        ChecksManager.resize(640, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(ChecksManager)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lay_tab = QtWidgets.QHBoxLayout()
        self.lay_tab.setSpacing(2)
        self.lay_tab.setObjectName("lay_tab")
        self.c_checks_tab = QtWidgets.QPushButton(parent=ChecksManager)
        self.c_checks_tab.setCheckable(True)
        self.c_checks_tab.setChecked(True)
        self.c_checks_tab.setObjectName("c_checks_tab")
        self.lay_tab.addWidget(self.c_checks_tab)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.lay_tab.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.lay_tab.addItem(spacerItem1)
        self.c_results_tab = QtWidgets.QPushButton(parent=ChecksManager)
        self.c_results_tab.setCheckable(True)
        self.c_results_tab.setChecked(False)
        self.c_results_tab.setObjectName("c_results_tab")
        self.lay_tab.addWidget(self.c_results_tab)
        self.verticalLayout.addLayout(self.lay_tab)
        self.c_stacked = QtWidgets.QStackedWidget(parent=ChecksManager)
        self.c_stacked.setContextMenuPolicy(
            QtCore.Qt.ContextMenuPolicy.NoContextMenu
        )
        self.c_stacked.setObjectName("c_stacked")
        self.page_checks = QtWidgets.QWidget()
        self.page_checks.setObjectName("page_checks")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_checks)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.l_available = QtWidgets.QLabel(parent=self.page_checks)
        self.l_available.setObjectName("l_available")
        self.verticalLayout_3.addWidget(self.l_available)
        self.c_available = QtWidgets.QTreeView(parent=self.page_checks)
        self.c_available.setObjectName("c_available")
        self.verticalLayout_3.addWidget(self.c_available)
        self.c_available_filter = QtWidgets.QLineEdit(parent=self.page_checks)
        self.c_available_filter.setClearButtonEnabled(True)
        self.c_available_filter.setObjectName("c_available_filter")
        self.verticalLayout_3.addWidget(self.c_available_filter)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_2.addItem(spacerItem2)
        self.c_add = QtWidgets.QPushButton(parent=self.page_checks)
        self.c_add.setObjectName("c_add")
        self.verticalLayout_2.addWidget(self.c_add)
        self.c_remove = QtWidgets.QPushButton(parent=self.page_checks)
        self.c_remove.setObjectName("c_remove")
        self.verticalLayout_2.addWidget(self.c_remove)
        spacerItem3 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.l_selected = QtWidgets.QLabel(parent=self.page_checks)
        self.l_selected.setObjectName("l_selected")
        self.verticalLayout_4.addWidget(self.l_selected)
        self.c_selected = QtWidgets.QTreeView(parent=self.page_checks)
        self.c_selected.setObjectName("c_selected")
        self.verticalLayout_4.addWidget(self.c_selected)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.c_stacked.addWidget(self.page_checks)
        self.page_results = QtWidgets.QWidget()
        self.page_results.setObjectName("page_results")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_results)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.splitter = QtWidgets.QSplitter(parent=self.page_results)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.page_results_left = QtWidgets.QWidget(parent=self.splitter)
        self.page_results_left.setObjectName("page_results_left")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_results_left)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.l_items = QtWidgets.QLabel(parent=self.page_results_left)
        self.l_items.setObjectName("l_items")
        self.verticalLayout_5.addWidget(self.l_items)
        self.c_results = QtWidgets.QTreeView(parent=self.page_results_left)
        self.c_results.setObjectName("c_results")
        self.verticalLayout_5.addWidget(self.c_results)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.c_results_filter = QtWidgets.QLineEdit(
            parent=self.page_results_left
        )
        self.c_results_filter.setClearButtonEnabled(True)
        self.c_results_filter.setObjectName("c_results_filter")
        self.horizontalLayout_2.addWidget(self.c_results_filter)
        self.c_type_filter = QtWidgets.QToolButton(
            parent=self.page_results_left
        )
        self.c_type_filter.setObjectName("c_type_filter")
        self.horizontalLayout_2.addWidget(self.c_type_filter)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.page_results_right = QtWidgets.QWidget(parent=self.splitter)
        self.page_results_right.setObjectName("page_results_right")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_results_right)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.l_details = QtWidgets.QLabel(parent=self.page_results_right)
        self.l_details.setObjectName("l_details")
        self.verticalLayout_6.addWidget(self.l_details)
        self.c_result_details = QtWidgets.QTextBrowser(
            parent=self.page_results_right
        )
        self.c_result_details.setObjectName("c_result_details")
        self.verticalLayout_6.addWidget(self.c_result_details)
        self.verticalLayout_7.addWidget(self.splitter)
        self.c_stacked.addWidget(self.page_results)
        self.verticalLayout.addWidget(self.c_stacked)
        self.c_progress = QtWidgets.QProgressBar(parent=ChecksManager)
        self.c_progress.setProperty("value", 24)
        self.c_progress.setObjectName("c_progress")
        self.verticalLayout.addWidget(self.c_progress)
        self.lay_button_box = QtWidgets.QHBoxLayout()
        self.lay_button_box.setObjectName("lay_button_box")
        spacerItem4 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.lay_button_box.addItem(spacerItem4)
        self.c_main_button = QtWidgets.QPushButton(parent=ChecksManager)
        self.c_main_button.setObjectName("c_main_button")
        self.lay_button_box.addWidget(self.c_main_button)
        self.c_cancel_button = QtWidgets.QPushButton(parent=ChecksManager)
        self.c_cancel_button.setObjectName("c_cancel_button")
        self.lay_button_box.addWidget(self.c_cancel_button)
        self.verticalLayout.addLayout(self.lay_button_box)

        self.retranslate_ui(ChecksManager)
        self.c_stacked.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ChecksManager)

    def retranslate_ui(self, ChecksManager):
        ChecksManager.setWindowTitle(
            self.ctx.t("gui.checks_manager.window_title", "ChecksManager")
        )
        self.c_checks_tab.setText(
            self.ctx.t("gui.checks_manager.c_checks_tab", "Checks")
        )
        self.c_results_tab.setText(
            self.ctx.t("gui.checks_manager.c_results_tab", "Results")
        )
        self.l_available.setText(
            self.ctx.t(
                "gui.checks_manager.l_available", "<b>Available checks</b>"
            )
        )
        self.c_available_filter.setPlaceholderText(
            self.ctx.t("gui.checks_manager.c_available_filter", "Filter")
        )
        self.c_add.setText(self.ctx.t("gui.checks_manager.c_add", "Add 🡆"))
        self.c_remove.setText(
            self.ctx.t("gui.checks_manager.c_remove", "🡄 Remove")
        )
        self.l_selected.setText(
            self.ctx.t(
                "gui.checks_manager.l_selected", "<b>Selected checks</b>"
            )
        )
        self.l_items.setText(self.ctx.t("gui.checks_manager.l_items", "Items"))
        self.c_results_filter.setPlaceholderText(
            self.ctx.t("gui.checks_manager.c_results_filter", "Filter")
        )
        self.c_type_filter.setText(
            self.ctx.t("gui.checks_manager.c_type_filter", "...")
        )
        self.l_details.setText(
            self.ctx.t("gui.checks_manager.l_details", "Details")
        )
        self.c_main_button.setText(
            self.ctx.t("gui.checks_manager.c_main_button", "Run")
        )
        self.c_cancel_button.setText(
            self.ctx.t("gui.checks_manager.c_cancel_button", "Cancel")
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_add,
            self.c_available,
            self.c_available_filter,
            self.c_cancel_button,
            self.c_checks_tab,
            self.c_main_button,
            self.c_progress,
            self.c_remove,
            self.c_result_details,
            self.c_results,
            self.c_results_filter,
            self.c_results_tab,
            self.c_selected,
            self.c_stacked,
            self.c_type_filter,
            self.page_checks,
            self.page_results,
            self.page_results_left,
            self.page_results_right,
            self.splitter,
        ]
