class Ui_ChecksManager:
    """Autogenerated content.

    Attributes:
        c_add: C add.
        c_available: C available.
        c_available_filter: C available filter.
        c_cancel_button: C cancel button.
        c_checks_tab: C checks tab.
        c_main_button: C main button.
        c_progress: C progress.
        c_remove: C remove.
        c_result_details: C result details.
        c_results: C results.
        c_results_filter: C results filter.
        c_results_tab: C results tab.
        c_selected: C selected.
        c_stacked: C stacked.
        c_type_filter: C type filter.
        horizontalLayout: The layout for the widget.
        horizontalLayout_2: The layout for the widget.
        horizontalSpacer: Horizontalspacer.
        lay_button_box: Lay button box.
        lay_tab: Lay tab.
        left_tab_spacer: Left tab spacer.
        page_checks: Page checks.
        page_results: Page results.
        page_results_left: Page results left.
        page_results_right: Page results right.
        right_tab_spacer: Right tab spacer.
        splitter: Splitter.
        verticalLayout: The layout for the widget.
        verticalLayout_2: The layout for the widget.
        verticalLayout_3: The layout for the widget.
        verticalLayout_4: The layout for the widget.
        verticalLayout_5: The layout for the widget.
        verticalLayout_6: The layout for the widget.
        verticalLayout_7: The layout for the widget.
        verticalSpacer: Verticalspacer.
        verticalSpacer_2: Verticalspacer 2.

    """

    c_add: "QPushButton"
    c_available: "QTreeView"
    c_available_filter: "QLineEdit"
    c_cancel_button: "QPushButton"
    c_checks_tab: "QPushButton"
    c_main_button: "QPushButton"
    c_progress: "QProgressBar"
    c_remove: "QPushButton"
    c_result_details: "QTextBrowser"
    c_results: "QTreeView"
    c_results_filter: "QLineEdit"
    c_results_tab: "QPushButton"
    c_selected: "QTreeView"
    c_stacked: "QStackedWidget"
    c_type_filter: "QToolButton"
    horizontalLayout: "QHBoxLayout"
    horizontalLayout_2: "QHBoxLayout"
    horizontalSpacer: "QSpacerItem"
    l_available: "QLabel"
    l_details: "QLabel"
    l_items: "QLabel"
    l_selected: "QLabel"
    lay_button_box: "QHBoxLayout"
    lay_tab: "QHBoxLayout"
    left_tab_spacer: "QSpacerItem"
    page_checks: "QWidget"
    page_results: "QWidget"
    page_results_left: "QWidget"
    page_results_right: "QWidget"
    right_tab_spacer: "QSpacerItem"
    splitter: "QSplitter"
    verticalLayout: "QVBoxLayout"
    verticalLayout_2: "QVBoxLayout"
    verticalLayout_3: "QVBoxLayout"
    verticalLayout_4: "QVBoxLayout"
    verticalLayout_5: "QVBoxLayout"
    verticalLayout_6: "QVBoxLayout"
    verticalLayout_7: "QVBoxLayout"
    verticalSpacer: "QSpacerItem"
    verticalSpacer_2: "QSpacerItem"

    def setup_ui(self, ChecksManager):

        if not ChecksManager.objectName():
            ChecksManager.setObjectName("ChecksManager")
        ChecksManager.resize(640, 480)
        self.verticalLayout = QVBoxLayout(ChecksManager)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lay_tab = QHBoxLayout()
        self.lay_tab.setSpacing(2)
        self.lay_tab.setObjectName("lay_tab")
        self.c_checks_tab = QPushButton(ChecksManager)
        self.c_checks_tab.setObjectName("c_checks_tab")
        self.c_checks_tab.setCheckable(True)
        self.c_checks_tab.setChecked(True)

        self.lay_tab.addWidget(self.c_checks_tab)

        self.left_tab_spacer = QSpacerItem(
            40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum
        )

        self.lay_tab.addItem(self.left_tab_spacer)

        self.right_tab_spacer = QSpacerItem(
            40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum
        )

        self.lay_tab.addItem(self.right_tab_spacer)

        self.c_results_tab = QPushButton(ChecksManager)
        self.c_results_tab.setObjectName("c_results_tab")
        self.c_results_tab.setCheckable(True)
        self.c_results_tab.setChecked(False)

        self.lay_tab.addWidget(self.c_results_tab)

        self.verticalLayout.addLayout(self.lay_tab)

        self.c_stacked = QStackedWidget(ChecksManager)
        self.c_stacked.setObjectName("c_stacked")
        self.c_stacked.setContextMenuPolicy(Qt.NoContextMenu)
        self.page_checks = QWidget()
        self.page_checks.setObjectName("page_checks")
        self.horizontalLayout = QHBoxLayout(self.page_checks)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.l_available = QLabel(self.page_checks)
        self.l_available.setObjectName("l_available")

        self.verticalLayout_3.addWidget(self.l_available)

        self.c_available = QTreeView(self.page_checks)
        self.c_available.setObjectName("c_available")

        self.verticalLayout_3.addWidget(self.c_available)

        self.c_available_filter = QLineEdit(self.page_checks)
        self.c_available_filter.setObjectName("c_available_filter")
        self.c_available_filter.setClearButtonEnabled(True)

        self.verticalLayout_3.addWidget(self.c_available_filter)

        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalSpacer = QSpacerItem(
            20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding
        )

        self.verticalLayout_2.addItem(self.verticalSpacer)

        self.c_add = QPushButton(self.page_checks)
        self.c_add.setObjectName("c_add")

        self.verticalLayout_2.addWidget(self.c_add)

        self.c_remove = QPushButton(self.page_checks)
        self.c_remove.setObjectName("c_remove")

        self.verticalLayout_2.addWidget(self.c_remove)

        self.verticalSpacer_2 = QSpacerItem(
            20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding
        )

        self.verticalLayout_2.addItem(self.verticalSpacer_2)

        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.verticalLayout_4 = QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.l_selected = QLabel(self.page_checks)
        self.l_selected.setObjectName("l_selected")

        self.verticalLayout_4.addWidget(self.l_selected)

        self.c_selected = QTreeView(self.page_checks)
        self.c_selected.setObjectName("c_selected")

        self.verticalLayout_4.addWidget(self.c_selected)

        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.c_stacked.addWidget(self.page_checks)
        self.page_results = QWidget()
        self.page_results.setObjectName("page_results")
        self.verticalLayout_7 = QVBoxLayout(self.page_results)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.splitter = QSplitter(self.page_results)
        self.splitter.setObjectName("splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.page_results_left = QWidget(self.splitter)
        self.page_results_left.setObjectName("page_results_left")
        self.verticalLayout_5 = QVBoxLayout(self.page_results_left)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.l_items = QLabel(self.page_results_left)
        self.l_items.setObjectName("l_items")

        self.verticalLayout_5.addWidget(self.l_items)

        self.c_results = QTreeView(self.page_results_left)
        self.c_results.setObjectName("c_results")

        self.verticalLayout_5.addWidget(self.c_results)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.c_results_filter = QLineEdit(self.page_results_left)
        self.c_results_filter.setObjectName("c_results_filter")
        self.c_results_filter.setClearButtonEnabled(True)

        self.horizontalLayout_2.addWidget(self.c_results_filter)

        self.c_type_filter = QToolButton(self.page_results_left)
        self.c_type_filter.setObjectName("c_type_filter")

        self.horizontalLayout_2.addWidget(self.c_type_filter)

        self.verticalLayout_5.addLayout(self.horizontalLayout_2)

        self.splitter.addWidget(self.page_results_left)
        self.page_results_right = QWidget(self.splitter)
        self.page_results_right.setObjectName("page_results_right")
        self.verticalLayout_6 = QVBoxLayout(self.page_results_right)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.l_details = QLabel(self.page_results_right)
        self.l_details.setObjectName("l_details")

        self.verticalLayout_6.addWidget(self.l_details)

        self.c_result_details = QTextBrowser(self.page_results_right)
        self.c_result_details.setObjectName("c_result_details")

        self.verticalLayout_6.addWidget(self.c_result_details)

        self.splitter.addWidget(self.page_results_right)

        self.verticalLayout_7.addWidget(self.splitter)

        self.c_stacked.addWidget(self.page_results)

        self.verticalLayout.addWidget(self.c_stacked)

        self.c_progress = QProgressBar(ChecksManager)
        self.c_progress.setObjectName("c_progress")
        self.c_progress.setValue(24)

        self.verticalLayout.addWidget(self.c_progress)

        self.lay_button_box = QHBoxLayout()
        self.lay_button_box.setObjectName("lay_button_box")
        self.horizontalSpacer = QSpacerItem(
            40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum
        )

        self.lay_button_box.addItem(self.horizontalSpacer)

        self.c_main_button = QPushButton(ChecksManager)
        self.c_main_button.setObjectName("c_main_button")

        self.lay_button_box.addWidget(self.c_main_button)

        self.c_cancel_button = QPushButton(ChecksManager)
        self.c_cancel_button.setObjectName("c_cancel_button")

        self.lay_button_box.addWidget(self.c_cancel_button)

        self.verticalLayout.addLayout(self.lay_button_box)

        self.retranslate_ui(ChecksManager)

        self.c_stacked.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(ChecksManager)

    # setupUi

    def retranslate_ui(self, ChecksManager):
        ChecksManager.setWindowTitle(
            QCoreApplication.translate("ChecksManager", "ChecksManager", None)
        )
        self.c_checks_tab.setText(
            QCoreApplication.translate("ChecksManager", "Checks", None)
        )
        self.c_results_tab.setText(
            QCoreApplication.translate("ChecksManager", "Results", None)
        )
        self.l_available.setText(
            QCoreApplication.translate(
                "ChecksManager", "<b>Available checks</b>", None
            )
        )
        self.c_available_filter.setPlaceholderText(
            QCoreApplication.translate("ChecksManager", "Filter", None)
        )
        self.c_add.setText(
            QCoreApplication.translate("ChecksManager", "Add \U0001f846", None)
        )
        self.c_remove.setText(
            QCoreApplication.translate(
                "ChecksManager", "\U0001f844 Remove", None
            )
        )
        self.l_selected.setText(
            QCoreApplication.translate(
                "ChecksManager", "<b>Selected checks</b>", None
            )
        )
        self.l_items.setText(
            QCoreApplication.translate("ChecksManager", "Items", None)
        )
        self.c_results_filter.setPlaceholderText(
            QCoreApplication.translate("ChecksManager", "Filter", None)
        )
        self.c_type_filter.setText(
            QCoreApplication.translate("ChecksManager", "...", None)
        )
        self.l_details.setText(
            QCoreApplication.translate("ChecksManager", "Details", None)
        )
        self.c_main_button.setText(
            QCoreApplication.translate("ChecksManager", "Run", None)
        )
        self.c_cancel_button.setText(
            QCoreApplication.translate("ChecksManager", "Cancel", None)
        )

    # retranslate_ui

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_add,
            self.c_available,
            self.c_available_filter,
            self.c_cancel_button,
            self.c_checks_tab,
            self.c_main_button,
            self.c_progress,
            self.c_remove,
            self.c_result_details,
            self.c_results,
            self.c_results_filter,
            self.c_results_tab,
            self.c_selected,
            self.c_stacked,
            self.c_type_filter,
            self.horizontalSpacer,
            self.left_tab_spacer,
            self.page_checks,
            self.page_results,
            self.page_results_left,
            self.page_results_right,
            self.right_tab_spacer,
            self.splitter,
            self.verticalSpacer,
            self.verticalSpacer_2,
        ]
