from typing import TYPE_CHECKING

from PyQt5 import QtCore, QtWidgets

if TYPE_CHECKING:
    from exdrf_qt.controls.templ_viewer.line_numbered_plain_text_edit import (
        LineNumberedPlainTextEdit,
    )


class Ui_TemplViewer:
    """Autogenerated content.

    Attributes:
        verticalLayout_4: The layout for the widget.
        c_splitter: C splitter.
        c_stacked: C stacked.
        page_viewer: Page viewer.
        verticalLayout_3: The layout for the widget.
        c_viewer: C viewer.
        page_editor: Page editor.
        verticalLayout_2: The layout for the widget.
        c_editor: C editor.
        layoutWidget: Layoutwidget.
        verticalLayout: The layout for the widget.
        c_vars: C vars.
        horizontalLayout: The layout for the widget.
        c_templ: C templ.
        c_sel_templ: C sel templ.

    """

    verticalLayout_4: "QtWidgets.QVBoxLayout"
    c_splitter: "QtWidgets.QSplitter"
    c_stacked: "QtWidgets.QStackedWidget"
    page_viewer: "QtWidgets.QWidget"
    verticalLayout_3: "QtWidgets.QVBoxLayout"
    c_viewer: "QtWidgets.QTextBrowser"
    page_editor: "QtWidgets.QWidget"
    verticalLayout_2: "QtWidgets.QVBoxLayout"
    c_editor: "LineNumberedPlainTextEdit"
    layoutWidget: "QtWidgets.QWidget"
    verticalLayout: "QtWidgets.QVBoxLayout"
    c_vars: "QtWidgets.QTreeView"
    horizontalLayout: "QtWidgets.QHBoxLayout"
    c_var_label: "QtWidgets.QLabel"
    c_templ: "QtWidgets.QLineEdit"
    c_sel_templ: "QtWidgets.QToolButton"

    def setup_ui(self, TemplViewer):
        from exdrf_qt.controls.templ_viewer.line_numbered_plain_text_edit import (
            LineNumberedPlainTextEdit,
        )

        TemplViewer.setObjectName("TemplViewer")
        TemplViewer.resize(640, 480)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(TemplViewer)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.c_splitter = QtWidgets.QSplitter(TemplViewer)
        self.c_splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.c_splitter.setLineWidth(0)
        self.c_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.c_splitter.setObjectName("c_splitter")
        self.c_stacked = QtWidgets.QStackedWidget(self.c_splitter)
        self.c_stacked.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.c_stacked.setFrameShadow(QtWidgets.QFrame.Plain)
        self.c_stacked.setLineWidth(0)
        self.c_stacked.setObjectName("c_stacked")
        self.page_viewer = QtWidgets.QWidget()
        self.page_viewer.setObjectName("page_viewer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_viewer)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.c_viewer = QtWidgets.QTextBrowser(self.page_viewer)
        self.c_viewer.setObjectName("c_viewer")
        self.verticalLayout_3.addWidget(self.c_viewer)
        self.c_stacked.addWidget(self.page_viewer)
        self.page_editor = QtWidgets.QWidget()
        self.page_editor.setObjectName("page_editor")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_editor)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.c_editor = LineNumberedPlainTextEdit(
            parent=self.page_editor, ctx=self.ctx
        )
        self.c_editor.setObjectName("c_editor")
        self.verticalLayout_2.addWidget(self.c_editor)
        self.c_stacked.addWidget(self.page_editor)
        self.layoutWidget = QtWidgets.QWidget(self.c_splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.c_vars = QtWidgets.QTreeView(self.layoutWidget)
        self.c_vars.setObjectName("c_vars")
        self.verticalLayout.addWidget(self.c_vars)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.c_var_label = QtWidgets.QLabel(self.layoutWidget)
        self.c_var_label.setObjectName("c_var_label")
        self.horizontalLayout.addWidget(self.c_var_label)
        self.c_templ = QtWidgets.QLineEdit(self.layoutWidget)
        self.c_templ.setObjectName("c_templ")
        self.horizontalLayout.addWidget(self.c_templ)
        self.c_sel_templ = QtWidgets.QToolButton(self.layoutWidget)
        self.c_sel_templ.setObjectName("c_sel_templ")
        self.horizontalLayout.addWidget(self.c_sel_templ)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.c_splitter)

        self.retranslate_ui(TemplViewer)
        self.c_stacked.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TemplViewer)

    def retranslate_ui(self, TemplViewer):
        _translate = QtCore.QCoreApplication.translate
        TemplViewer.setWindowTitle(
            _translate("TemplViewer", "Template with data")
        )
        self.c_var_label.setText(_translate("TemplViewer", "Template"))
        self.c_sel_templ.setText(_translate("TemplViewer", "..."))

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_splitter,
            self.c_stacked,
            self.page_viewer,
            self.c_viewer,
            self.page_editor,
            self.c_editor,
            self.layoutWidget,
            self.c_vars,
            self.c_templ,
            self.c_sel_templ,
        ]
