from typing import TYPE_CHECKING

from PyQt5 import QtCore, QtWidgets

if TYPE_CHECKING:
    from exdrf_qt.field_ed.api import (
        DrfIntEditor,
        DrfLineEditor,
        QtCompositeKeyModelSiSe,
    )


class Ui_QtRelatedItemEditor:
    """Autogenerated content.

    Attributes:
        verticalLayout: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        formLayout: The layout for the widget.
        c_comp_key_owner: C comp key owner.
        c_comp_key_part1: C comp key part1.
        c_comp_key_part2: C comp key part2.
        c_id: C id.
        c_item_data: C item data.
        c_some_int: C some int.

    """

    verticalLayout: "QtWidgets.QVBoxLayout"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    formLayout: "QtWidgets.QFormLayout"
    lbl_comp_key_owner: "QtWidgets.QLabel"
    c_comp_key_owner: "QtCompositeKeyModelSiSe"
    lbl_comp_key_part1: "QtWidgets.QLabel"
    c_comp_key_part1: "DrfLineEditor"
    lbl_comp_key_part2: "QtWidgets.QLabel"
    c_comp_key_part2: "DrfIntEditor"
    lbl_id: "QtWidgets.QLabel"
    c_id: "DrfIntEditor"
    lbl_item_data: "QtWidgets.QLabel"
    c_item_data: "DrfLineEditor"
    lbl_some_int: "QtWidgets.QLabel"
    c_some_int: "DrfIntEditor"

    def setup_ui(self, QtRelatedItemEditor):
        from exdrf_qt.field_ed.api import (
            DrfIntEditor,
            DrfLineEditor,
            QtCompositeKeyModelSiSe,
        )

        QtRelatedItemEditor.setObjectName("QtRelatedItemEditor")
        QtRelatedItemEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(QtRelatedItemEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(QtRelatedItemEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_comp_key_owner = QtWidgets.QLabel(self.tab_general)
        self.lbl_comp_key_owner.setObjectName("lbl_comp_key_owner")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_comp_key_owner
        )
        self.c_comp_key_owner = QtCompositeKeyModelSiSe(
            parent=self.tab_general, ctx=self.ctx
        )
        self.c_comp_key_owner.setObjectName("c_comp_key_owner")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_comp_key_owner
        )
        self.lbl_comp_key_part1 = QtWidgets.QLabel(self.tab_general)
        self.lbl_comp_key_part1.setObjectName("lbl_comp_key_part1")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.lbl_comp_key_part1
        )
        self.c_comp_key_part1 = DrfLineEditor(
            parent=self.tab_general, ctx=self.ctx
        )
        self.c_comp_key_part1.setObjectName("c_comp_key_part1")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.c_comp_key_part1
        )
        self.lbl_comp_key_part2 = QtWidgets.QLabel(self.tab_general)
        self.lbl_comp_key_part2.setObjectName("lbl_comp_key_part2")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.lbl_comp_key_part2
        )
        self.c_comp_key_part2 = DrfIntEditor(
            parent=self.tab_general, ctx=self.ctx
        )
        self.c_comp_key_part2.setObjectName("c_comp_key_part2")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.c_comp_key_part2
        )
        self.lbl_id = QtWidgets.QLabel(self.tab_general)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.lbl_id
        )
        self.c_id = DrfIntEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_id.setObjectName("c_id")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.c_id)
        self.lbl_item_data = QtWidgets.QLabel(self.tab_general)
        self.lbl_item_data.setObjectName("lbl_item_data")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.lbl_item_data
        )
        self.c_item_data = DrfLineEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_item_data.setObjectName("c_item_data")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.FieldRole, self.c_item_data
        )
        self.lbl_some_int = QtWidgets.QLabel(self.tab_general)
        self.lbl_some_int.setObjectName("lbl_some_int")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.LabelRole, self.lbl_some_int
        )
        self.c_some_int = DrfIntEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_some_int.setObjectName("c_some_int")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.FieldRole, self.c_some_int
        )
        self.main_tab.addTab(self.tab_general, "")
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtRelatedItemEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtRelatedItemEditor)

    def retranslate_ui(self, QtRelatedItemEditor):
        _translate = QtCore.QCoreApplication.translate
        QtRelatedItemEditor.setWindowTitle(
            _translate("QtRelatedItemEditor", "Related item Editor")
        )
        self.lbl_comp_key_owner.setText(
            _translate("QtRelatedItemEditor", "Comp Key Owner ")
        )
        self.lbl_comp_key_part1.setText(
            _translate("QtRelatedItemEditor", "Comp Key Part1 ")
        )
        self.lbl_comp_key_part2.setText(
            _translate("QtRelatedItemEditor", "Comp Key Part2 ")
        )
        self.lbl_id.setText(_translate("QtRelatedItemEditor", "Id "))
        self.lbl_item_data.setText(
            _translate("QtRelatedItemEditor", "Item Data ")
        )
        self.lbl_some_int.setText(
            _translate("QtRelatedItemEditor", "Some Int ")
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            _translate("QtRelatedItemEditor", "General"),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.main_tab,
            self.tab_general,
            self.c_comp_key_owner,
            self.c_comp_key_part1,
            self.c_comp_key_part2,
            self.c_id,
            self.c_item_data,
            self.c_some_int,
        ]
