from typing import Any

from PyQt6 import QtCore, QtWidgets


class Ui_SelectDatabase:
    """Autogenerated content.

    Attributes:
        bbox: Bbox.
        c_backend: C backend.
        c_browse_file: C browse file.
        c_db_name: C db name.
        c_file_path: C file path.
        c_host: C host.
        c_list: C list.
        c_pass: C pass.
        c_port: C port.
        c_schema: C schema.
        c_username: C username.
        formLayout: The layout for the widget.
        horizontalLayout: The layout for the widget.
        main_tab: Main tab.
        tab_local: Tab local.
        tab_manage: Tab manage.
        tab_remote: Tab remote.
        verticalLayout: The layout for the widget.
        verticalLayout_2: The layout for the widget.
        verticalLayout_3: The layout for the widget.

    """

    bbox: "QtWidgets.QDialogButtonBox"
    c_backend: "QtWidgets.QComboBox"
    c_browse_file: "QtWidgets.QToolButton"
    c_db_name: "QtWidgets.QLineEdit"
    c_file_path: "QtWidgets.QLineEdit"
    c_host: "QtWidgets.QLineEdit"
    c_list: "QtWidgets.QTreeView"
    c_pass: "QtWidgets.QLineEdit"
    c_port: "QtWidgets.QLineEdit"
    c_schema: "QtWidgets.QLineEdit"
    c_username: "QtWidgets.QLineEdit"
    formLayout: "QtWidgets.QFormLayout"
    horizontalLayout: "QtWidgets.QHBoxLayout"
    l_file_path: "QtWidgets.QLabel"
    label: "QtWidgets.QLabel"
    label_2: "QtWidgets.QLabel"
    label_3: "QtWidgets.QLabel"
    label_4: "QtWidgets.QLabel"
    label_5: "QtWidgets.QLabel"
    label_6: "QtWidgets.QLabel"
    label_7: "QtWidgets.QLabel"
    label_8: "QtWidgets.QLabel"
    main_tab: "QtWidgets.QTabWidget"
    tab_local: "QtWidgets.QWidget"
    tab_manage: "QtWidgets.QWidget"
    tab_remote: "QtWidgets.QWidget"
    verticalLayout: "QtWidgets.QVBoxLayout"
    verticalLayout_2: "QtWidgets.QVBoxLayout"
    verticalLayout_3: "QtWidgets.QVBoxLayout"
    ctx: "Any"  # Injected by host widget when used as mixin

    def setup_ui(self, SelectDatabase):

        SelectDatabase.setObjectName("SelectDatabase")
        SelectDatabase.resize(376, 338)
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectDatabase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(parent=SelectDatabase)
        self.main_tab.setObjectName("main_tab")
        self.tab_local = QtWidgets.QWidget()
        self.tab_local.setObjectName("tab_local")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_local)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_file_path = QtWidgets.QLabel(parent=self.tab_local)
        self.l_file_path.setObjectName("l_file_path")
        self.horizontalLayout.addWidget(self.l_file_path)
        self.c_file_path = QtWidgets.QLineEdit(parent=self.tab_local)
        self.c_file_path.setObjectName("c_file_path")
        self.horizontalLayout.addWidget(self.c_file_path)
        self.c_browse_file = QtWidgets.QToolButton(parent=self.tab_local)
        self.c_browse_file.setObjectName("c_browse_file")
        self.horizontalLayout.addWidget(self.c_browse_file)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_2.addItem(spacerItem)
        self.main_tab.addTab(self.tab_local, "")
        self.tab_remote = QtWidgets.QWidget()
        self.tab_remote.setObjectName("tab_remote")
        self.formLayout = QtWidgets.QFormLayout(self.tab_remote)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.tab_remote)
        self.label.setObjectName("label")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label
        )
        self.c_backend = QtWidgets.QComboBox(parent=self.tab_remote)
        self.c_backend.setObjectName("c_backend")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.c_backend
        )
        self.label_2 = QtWidgets.QLabel(parent=self.tab_remote)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2
        )
        self.c_username = QtWidgets.QLineEdit(parent=self.tab_remote)
        self.c_username.setObjectName("c_username")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.c_username
        )
        self.label_3 = QtWidgets.QLabel(parent=self.tab_remote)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3
        )
        self.label_5 = QtWidgets.QLabel(parent=self.tab_remote)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5
        )
        self.label_4 = QtWidgets.QLabel(parent=self.tab_remote)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4
        )
        self.label_6 = QtWidgets.QLabel(parent=self.tab_remote)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6
        )
        self.label_7 = QtWidgets.QLabel(parent=self.tab_remote)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(
            6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7
        )
        self.c_host = QtWidgets.QLineEdit(parent=self.tab_remote)
        self.c_host.setObjectName("c_host")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.c_host
        )
        self.c_pass = QtWidgets.QLineEdit(parent=self.tab_remote)
        self.c_pass.setObjectName("c_pass")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.c_pass
        )
        self.c_port = QtWidgets.QLineEdit(parent=self.tab_remote)
        self.c_port.setObjectName("c_port")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.c_port
        )
        self.c_db_name = QtWidgets.QLineEdit(parent=self.tab_remote)
        self.c_db_name.setObjectName("c_db_name")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.c_db_name
        )
        self.c_schema = QtWidgets.QLineEdit(parent=self.tab_remote)
        self.c_schema.setObjectName("c_schema")
        self.formLayout.setWidget(
            6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.c_schema
        )
        self.main_tab.addTab(self.tab_remote, "")
        self.tab_manage = QtWidgets.QWidget()
        self.tab_manage.setObjectName("tab_manage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_manage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.c_list = QtWidgets.QTreeView(parent=self.tab_manage)
        self.c_list.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked
            | QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed
        )
        self.c_list.setRootIsDecorated(False)
        self.c_list.setUniformRowHeights(True)
        self.c_list.setSortingEnabled(True)
        self.c_list.setObjectName("c_list")
        self.verticalLayout_3.addWidget(self.c_list)
        self.main_tab.addTab(self.tab_manage, "")
        self.verticalLayout.addWidget(self.main_tab)
        self.label_8 = QtWidgets.QLabel(parent=SelectDatabase)
        self.label_8.setWordWrap(True)
        self.label_8.setTextInteractionFlags(
            QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse
            | QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard
            | QtCore.Qt.TextInteractionFlag.TextSelectableByMouse
        )
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.bbox = QtWidgets.QDialogButtonBox(parent=SelectDatabase)
        self.bbox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.bbox.setObjectName("bbox")
        self.verticalLayout.addWidget(self.bbox)

        self.retranslate_ui(SelectDatabase)
        self.main_tab.setCurrentIndex(2)
        self.bbox.accepted.connect(SelectDatabase.accept)  # type: ignore
        self.bbox.rejected.connect(SelectDatabase.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelectDatabase)

    def retranslate_ui(self, SelectDatabase):
        SelectDatabase.setWindowTitle(
            self.ctx.t("gui.select_database.window_title", "Dialog")
        )
        self.l_file_path.setText(
            self.ctx.t("gui.select_database.l_file_path", "File Path")
        )
        self.c_browse_file.setText(
            self.ctx.t("gui.select_database.c_browse_file", "...")
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_local),
            self.ctx.t("gui.select_database.tab_local", "Local"),
        )
        self.label.setText(self.ctx.t("gui.select_database.label", "Backend"))
        self.label_2.setText(
            self.ctx.t("gui.select_database.label_2", "User name")
        )
        self.label_3.setText(
            self.ctx.t("gui.select_database.label_3", "Password")
        )
        self.label_5.setText(
            self.ctx.t("gui.select_database.label_5", "Host address")
        )
        self.label_4.setText(
            self.ctx.t("gui.select_database.label_4", "Host port")
        )
        self.label_6.setText(
            self.ctx.t("gui.select_database.label_6", "Database")
        )
        self.label_7.setText(
            self.ctx.t("gui.select_database.label_7", "Schema")
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_remote),
            self.ctx.t("gui.select_database.tab_remote", "Remote"),
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_manage),
            self.ctx.t("gui.select_database.tab_manage", "Manage"),
        )
        self.label_8.setText(
            self.ctx.t(
                "gui.select_database.label_8",
                "To avoid seeing this dialog at startup, set the "
                "EXDRF_DB_CONN_STRING and EXDRF_DB_SCHEMA "
                "environment variables.",
            )
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.bbox,
            self.c_backend,
            self.c_browse_file,
            self.c_db_name,
            self.c_file_path,
            self.c_host,
            self.c_list,
            self.c_pass,
            self.c_port,
            self.c_schema,
            self.c_username,
            self.main_tab,
            self.tab_local,
            self.tab_manage,
            self.tab_remote,
        ]
