from PyQt5 import QtCore, QtWidgets


class Ui_SelectDatabase:
    """Autogenerated content.

    Attributes:
        verticalLayout: The layout for the widget.
        main_tab: Main tab.
        tab_local: Tab local.
        verticalLayout_2: The layout for the widget.
        horizontalLayout: The layout for the widget.
        c_file_path: C file path.
        c_browse_file: C browse file.
        tab_remote: Tab remote.
        formLayout: The layout for the widget.
        c_backend: C backend.
        c_username: C username.
        c_host: C host.
        c_pass: C pass.
        c_port: C port.
        c_db_name: C db name.
        c_schema: C schema.
        tab_manage: Tab manage.
        verticalLayout_3: The layout for the widget.
        c_list: C list.
        bbox: Bbox.

    """

    verticalLayout: "QtWidgets.QVBoxLayout"
    main_tab: "QtWidgets.QTabWidget"
    tab_local: "QtWidgets.QWidget"
    verticalLayout_2: "QtWidgets.QVBoxLayout"
    horizontalLayout: "QtWidgets.QHBoxLayout"
    l_file_path: "QtWidgets.QLabel"
    c_file_path: "QtWidgets.QLineEdit"
    c_browse_file: "QtWidgets.QToolButton"
    tab_remote: "QtWidgets.QWidget"
    formLayout: "QtWidgets.QFormLayout"
    label: "QtWidgets.QLabel"
    c_backend: "QtWidgets.QComboBox"
    label_2: "QtWidgets.QLabel"
    c_username: "QtWidgets.QLineEdit"
    label_3: "QtWidgets.QLabel"
    label_5: "QtWidgets.QLabel"
    label_4: "QtWidgets.QLabel"
    label_6: "QtWidgets.QLabel"
    label_7: "QtWidgets.QLabel"
    c_host: "QtWidgets.QLineEdit"
    c_pass: "QtWidgets.QLineEdit"
    c_port: "QtWidgets.QLineEdit"
    c_db_name: "QtWidgets.QLineEdit"
    c_schema: "QtWidgets.QLineEdit"
    tab_manage: "QtWidgets.QWidget"
    verticalLayout_3: "QtWidgets.QVBoxLayout"
    c_list: "QtWidgets.QTreeView"
    label_8: "QtWidgets.QLabel"
    bbox: "QtWidgets.QDialogButtonBox"

    def setup_ui(self, SelectDatabase):

        SelectDatabase.setObjectName("SelectDatabase")
        SelectDatabase.resize(376, 338)
        self.verticalLayout = QtWidgets.QVBoxLayout(SelectDatabase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(SelectDatabase)
        self.main_tab.setObjectName("main_tab")
        self.tab_local = QtWidgets.QWidget()
        self.tab_local.setObjectName("tab_local")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_local)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_file_path = QtWidgets.QLabel(self.tab_local)
        self.l_file_path.setObjectName("l_file_path")
        self.horizontalLayout.addWidget(self.l_file_path)
        self.c_file_path = QtWidgets.QLineEdit(self.tab_local)
        self.c_file_path.setObjectName("c_file_path")
        self.horizontalLayout.addWidget(self.c_file_path)
        self.c_browse_file = QtWidgets.QToolButton(self.tab_local)
        self.c_browse_file.setObjectName("c_browse_file")
        self.horizontalLayout.addWidget(self.c_browse_file)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Minimum,
            QtWidgets.QSizePolicy.Expanding,
        )
        self.verticalLayout_2.addItem(spacerItem)
        self.main_tab.addTab(self.tab_local, "")
        self.tab_remote = QtWidgets.QWidget()
        self.tab_remote.setObjectName("tab_remote")
        self.formLayout = QtWidgets.QFormLayout(self.tab_remote)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.tab_remote)
        self.label.setObjectName("label")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.label
        )
        self.c_backend = QtWidgets.QComboBox(self.tab_remote)
        self.c_backend.setObjectName("c_backend")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_backend
        )
        self.label_2 = QtWidgets.QLabel(self.tab_remote)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.label_2
        )
        self.c_username = QtWidgets.QLineEdit(self.tab_remote)
        self.c_username.setObjectName("c_username")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.c_username
        )
        self.label_3 = QtWidgets.QLabel(self.tab_remote)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.label_3
        )
        self.label_5 = QtWidgets.QLabel(self.tab_remote)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.label_5
        )
        self.label_4 = QtWidgets.QLabel(self.tab_remote)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.label_4
        )
        self.label_6 = QtWidgets.QLabel(self.tab_remote)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.LabelRole, self.label_6
        )
        self.label_7 = QtWidgets.QLabel(self.tab_remote)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(
            6, QtWidgets.QFormLayout.LabelRole, self.label_7
        )
        self.c_host = QtWidgets.QLineEdit(self.tab_remote)
        self.c_host.setObjectName("c_host")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.c_host
        )
        self.c_pass = QtWidgets.QLineEdit(self.tab_remote)
        self.c_pass.setObjectName("c_pass")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.c_pass
        )
        self.c_port = QtWidgets.QLineEdit(self.tab_remote)
        self.c_port.setObjectName("c_port")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.FieldRole, self.c_port
        )
        self.c_db_name = QtWidgets.QLineEdit(self.tab_remote)
        self.c_db_name.setObjectName("c_db_name")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.FieldRole, self.c_db_name
        )
        self.c_schema = QtWidgets.QLineEdit(self.tab_remote)
        self.c_schema.setObjectName("c_schema")
        self.formLayout.setWidget(
            6, QtWidgets.QFormLayout.FieldRole, self.c_schema
        )
        self.main_tab.addTab(self.tab_remote, "")
        self.tab_manage = QtWidgets.QWidget()
        self.tab_manage.setObjectName("tab_manage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_manage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.c_list = QtWidgets.QTreeView(self.tab_manage)
        self.c_list.setEditTriggers(
            QtWidgets.QAbstractItemView.DoubleClicked
            | QtWidgets.QAbstractItemView.EditKeyPressed
        )
        self.c_list.setRootIsDecorated(False)
        self.c_list.setUniformRowHeights(True)
        self.c_list.setSortingEnabled(True)
        self.c_list.setObjectName("c_list")
        self.verticalLayout_3.addWidget(self.c_list)
        self.main_tab.addTab(self.tab_manage, "")
        self.verticalLayout.addWidget(self.main_tab)
        self.label_8 = QtWidgets.QLabel(SelectDatabase)
        self.label_8.setWordWrap(True)
        self.label_8.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByMouse
            | QtCore.Qt.TextSelectableByKeyboard
            | QtCore.Qt.TextSelectableByMouse
        )
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.bbox = QtWidgets.QDialogButtonBox(SelectDatabase)
        self.bbox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.bbox.setObjectName("bbox")
        self.verticalLayout.addWidget(self.bbox)

        self.retranslate_ui(SelectDatabase)
        self.main_tab.setCurrentIndex(2)
        self.bbox.accepted.connect(SelectDatabase.accept)  # type: ignore
        self.bbox.rejected.connect(SelectDatabase.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SelectDatabase)

    def retranslate_ui(self, SelectDatabase):
        _translate = QtCore.QCoreApplication.translate
        SelectDatabase.setWindowTitle(_translate("SelectDatabase", "Dialog"))
        self.l_file_path.setText(_translate("SelectDatabase", "File Path"))
        self.c_browse_file.setText(_translate("SelectDatabase", "..."))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_local),
            _translate("SelectDatabase", "Local"),
        )
        self.label.setText(_translate("SelectDatabase", "Backend"))
        self.label_2.setText(_translate("SelectDatabase", "User name"))
        self.label_3.setText(_translate("SelectDatabase", "Password"))
        self.label_5.setText(_translate("SelectDatabase", "Host address"))
        self.label_4.setText(_translate("SelectDatabase", "Host port"))
        self.label_6.setText(_translate("SelectDatabase", "Database"))
        self.label_7.setText(_translate("SelectDatabase", "Schema"))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_remote),
            _translate("SelectDatabase", "Remote"),
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_manage),
            _translate("SelectDatabase", "Manage"),
        )
        self.label_8.setText(
            _translate(
                "SelectDatabase",
                "To avoid seeing this dialog at startup, set the "
                "EXDRF_DB_CONN_STRING and EXDRF_DB_SCHEMA environment "
                "variables.",
            )
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.main_tab,
            self.tab_local,
            self.c_file_path,
            self.c_browse_file,
            self.tab_remote,
            self.c_backend,
            self.c_username,
            self.c_host,
            self.c_pass,
            self.c_port,
            self.c_db_name,
            self.c_schema,
            self.tab_manage,
            self.c_list,
            self.bbox,
        ]
