class Ui_SelectDatabase:
    """Autogenerated content.

    Attributes:
        bbox: Bbox.
        c_backend: C backend.
        c_browse_file: C browse file.
        c_db_name: C db name.
        c_file_path: C file path.
        c_host: C host.
        c_list: C list.
        c_pass: C pass.
        c_port: C port.
        c_schema: C schema.
        c_username: C username.
        formLayout: The layout for the widget.
        horizontalLayout: The layout for the widget.
        main_tab: Main tab.
        tab_local: Tab local.
        tab_manage: Tab manage.
        tab_remote: Tab remote.
        verticalLayout: The layout for the widget.
        verticalLayout_2: The layout for the widget.
        verticalLayout_3: The layout for the widget.
        verticalSpacer: Verticalspacer.

    """

    bbox: "QDialogButtonBox"
    c_backend: "QComboBox"
    c_browse_file: "QToolButton"
    c_db_name: "QLineEdit"
    c_file_path: "QLineEdit"
    c_host: "QLineEdit"
    c_list: "QTreeView"
    c_pass: "QLineEdit"
    c_port: "QLineEdit"
    c_schema: "QLineEdit"
    c_username: "QLineEdit"
    formLayout: "QFormLayout"
    horizontalLayout: "QHBoxLayout"
    l_file_path: "QLabel"
    label: "QLabel"
    label_2: "QLabel"
    label_3: "QLabel"
    label_4: "QLabel"
    label_5: "QLabel"
    label_6: "QLabel"
    label_7: "QLabel"
    label_8: "QLabel"
    main_tab: "QTabWidget"
    tab_local: "QWidget"
    tab_manage: "QWidget"
    tab_remote: "QWidget"
    verticalLayout: "QVBoxLayout"
    verticalLayout_2: "QVBoxLayout"
    verticalLayout_3: "QVBoxLayout"
    verticalSpacer: "QSpacerItem"

    def setup_ui(self, SelectDatabase):

        if not SelectDatabase.objectName():
            SelectDatabase.setObjectName("SelectDatabase")
        SelectDatabase.resize(376, 338)
        self.verticalLayout = QVBoxLayout(SelectDatabase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QTabWidget(SelectDatabase)
        self.main_tab.setObjectName("main_tab")
        self.tab_local = QWidget()
        self.tab_local.setObjectName("tab_local")
        self.verticalLayout_2 = QVBoxLayout(self.tab_local)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_file_path = QLabel(self.tab_local)
        self.l_file_path.setObjectName("l_file_path")

        self.horizontalLayout.addWidget(self.l_file_path)

        self.c_file_path = QLineEdit(self.tab_local)
        self.c_file_path.setObjectName("c_file_path")

        self.horizontalLayout.addWidget(self.c_file_path)

        self.c_browse_file = QToolButton(self.tab_local)
        self.c_browse_file.setObjectName("c_browse_file")

        self.horizontalLayout.addWidget(self.c_browse_file)

        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.verticalSpacer = QSpacerItem(
            20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding
        )

        self.verticalLayout_2.addItem(self.verticalSpacer)

        self.main_tab.addTab(self.tab_local, "")
        self.tab_remote = QWidget()
        self.tab_remote.setObjectName("tab_remote")
        self.formLayout = QFormLayout(self.tab_remote)
        self.formLayout.setObjectName("formLayout")
        self.label = QLabel(self.tab_remote)
        self.label.setObjectName("label")

        self.formLayout.setWidget(0, QFormLayout.ItemRole.LabelRole, self.label)

        self.c_backend = QComboBox(self.tab_remote)
        self.c_backend.setObjectName("c_backend")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.c_backend
        )

        self.label_2 = QLabel(self.tab_remote)
        self.label_2.setObjectName("label_2")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.LabelRole, self.label_2
        )

        self.c_username = QLineEdit(self.tab_remote)
        self.c_username.setObjectName("c_username")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.FieldRole, self.c_username
        )

        self.label_3 = QLabel(self.tab_remote)
        self.label_3.setObjectName("label_3")

        self.formLayout.setWidget(
            2, QFormLayout.ItemRole.LabelRole, self.label_3
        )

        self.label_5 = QLabel(self.tab_remote)
        self.label_5.setObjectName("label_5")

        self.formLayout.setWidget(
            3, QFormLayout.ItemRole.LabelRole, self.label_5
        )

        self.label_4 = QLabel(self.tab_remote)
        self.label_4.setObjectName("label_4")

        self.formLayout.setWidget(
            4, QFormLayout.ItemRole.LabelRole, self.label_4
        )

        self.label_6 = QLabel(self.tab_remote)
        self.label_6.setObjectName("label_6")

        self.formLayout.setWidget(
            5, QFormLayout.ItemRole.LabelRole, self.label_6
        )

        self.label_7 = QLabel(self.tab_remote)
        self.label_7.setObjectName("label_7")

        self.formLayout.setWidget(
            6, QFormLayout.ItemRole.LabelRole, self.label_7
        )

        self.c_host = QLineEdit(self.tab_remote)
        self.c_host.setObjectName("c_host")

        self.formLayout.setWidget(
            3, QFormLayout.ItemRole.FieldRole, self.c_host
        )

        self.c_pass = QLineEdit(self.tab_remote)
        self.c_pass.setObjectName("c_pass")

        self.formLayout.setWidget(
            2, QFormLayout.ItemRole.FieldRole, self.c_pass
        )

        self.c_port = QLineEdit(self.tab_remote)
        self.c_port.setObjectName("c_port")

        self.formLayout.setWidget(
            4, QFormLayout.ItemRole.FieldRole, self.c_port
        )

        self.c_db_name = QLineEdit(self.tab_remote)
        self.c_db_name.setObjectName("c_db_name")

        self.formLayout.setWidget(
            5, QFormLayout.ItemRole.FieldRole, self.c_db_name
        )

        self.c_schema = QLineEdit(self.tab_remote)
        self.c_schema.setObjectName("c_schema")

        self.formLayout.setWidget(
            6, QFormLayout.ItemRole.FieldRole, self.c_schema
        )

        self.main_tab.addTab(self.tab_remote, "")
        self.tab_manage = QWidget()
        self.tab_manage.setObjectName("tab_manage")
        self.verticalLayout_3 = QVBoxLayout(self.tab_manage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.c_list = QTreeView(self.tab_manage)
        self.c_list.setObjectName("c_list")
        self.c_list.setEditTriggers(
            QAbstractItemView.DoubleClicked | QAbstractItemView.EditKeyPressed
        )
        self.c_list.setRootIsDecorated(False)
        self.c_list.setUniformRowHeights(True)
        self.c_list.setSortingEnabled(True)

        self.verticalLayout_3.addWidget(self.c_list)

        self.main_tab.addTab(self.tab_manage, "")

        self.verticalLayout.addWidget(self.main_tab)

        self.label_8 = QLabel(SelectDatabase)
        self.label_8.setObjectName("label_8")
        self.label_8.setWordWrap(True)
        self.label_8.setTextInteractionFlags(
            Qt.LinksAccessibleByMouse
            | Qt.TextSelectableByKeyboard
            | Qt.TextSelectableByMouse
        )

        self.verticalLayout.addWidget(self.label_8)

        self.bbox = QDialogButtonBox(SelectDatabase)
        self.bbox.setObjectName("bbox")
        self.bbox.setStandardButtons(
            QDialogButtonBox.Cancel | QDialogButtonBox.Ok
        )

        self.verticalLayout.addWidget(self.bbox)

        self.retranslate_ui(SelectDatabase)
        self.bbox.accepted.connect(SelectDatabase.accept)
        self.bbox.rejected.connect(SelectDatabase.reject)

        self.main_tab.setCurrentIndex(2)

        QMetaObject.connectSlotsByName(SelectDatabase)

    # setupUi

    def retranslate_ui(self, SelectDatabase):
        SelectDatabase.setWindowTitle(
            QCoreApplication.translate("SelectDatabase", "Dialog", None)
        )
        self.l_file_path.setText(
            QCoreApplication.translate("SelectDatabase", "File Path", None)
        )
        self.c_browse_file.setText(
            QCoreApplication.translate("SelectDatabase", "...", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_local),
            QCoreApplication.translate("SelectDatabase", "Local", None),
        )
        self.label.setText(
            QCoreApplication.translate("SelectDatabase", "Backend", None)
        )
        self.label_2.setText(
            QCoreApplication.translate("SelectDatabase", "User name", None)
        )
        self.label_3.setText(
            QCoreApplication.translate("SelectDatabase", "Password", None)
        )
        self.label_5.setText(
            QCoreApplication.translate("SelectDatabase", "Host address", None)
        )
        self.label_4.setText(
            QCoreApplication.translate("SelectDatabase", "Host port", None)
        )
        self.label_6.setText(
            QCoreApplication.translate("SelectDatabase", "Database", None)
        )
        self.label_7.setText(
            QCoreApplication.translate("SelectDatabase", "Schema", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_remote),
            QCoreApplication.translate("SelectDatabase", "Remote", None),
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_manage),
            QCoreApplication.translate("SelectDatabase", "Manage", None),
        )
        self.label_8.setText(
            QCoreApplication.translate(
                "SelectDatabase",
                "To avoid seeing this dialog at startup, set the "
                "EXDRF_DB_CONN_STRING and EXDRF_DB_SCHEMA environment "
                "variables.",
                None,
            )
        )

    # retranslate_ui

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.bbox,
            self.c_backend,
            self.c_browse_file,
            self.c_db_name,
            self.c_file_path,
            self.c_host,
            self.c_list,
            self.c_pass,
            self.c_port,
            self.c_schema,
            self.c_username,
            self.main_tab,
            self.tab_local,
            self.tab_manage,
            self.tab_remote,
            self.verticalSpacer,
        ]
