class Ui_QtTagEditor:
    """Autogenerated content.

    Attributes:
        c_id: C id.
        c_name: C name.
        c_parents: C parents.
        formLayout: The layout for the widget.
        formLayout1: The layout for the widget.
        formLayout2: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        tab_info: Tab info.
        tab_relations: Tab relations.
        verticalLayout: The layout for the widget.

    """

    c_id: "QSpinBox"
    c_name: "QLineEdit"
    c_parents: "QCheckBox"
    formLayout: "QFormLayout"
    formLayout1: "QFormLayout"
    formLayout2: "QFormLayout"
    lbl_id: "QLabel"
    lbl_name: "QLabel"
    lbl_parents: "QLabel"
    main_tab: "QTabWidget"
    tab_general: "QWidget"
    tab_info: "QWidget"
    tab_relations: "QWidget"
    verticalLayout: "QVBoxLayout"

    def setup_ui(self, QtTagEditor):

        if not QtTagEditor.objectName():
            QtTagEditor.setObjectName("QtTagEditor")
        QtTagEditor.resize(480, 640)
        self.verticalLayout = QVBoxLayout(QtTagEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QTabWidget(QtTagEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_name = QLabel(self.tab_general)
        self.lbl_name.setObjectName("lbl_name")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_name
        )

        self.c_name = QLineEdit(self.tab_general)
        self.c_name.setObjectName("c_name")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.c_name
        )

        self.main_tab.addTab(self.tab_general, "")
        self.tab_relations = QWidget()
        self.tab_relations.setObjectName("tab_relations")
        self.formLayout1 = QFormLayout(self.tab_relations)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_parents = QLabel(self.tab_relations)
        self.lbl_parents.setObjectName("lbl_parents")

        self.formLayout1.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_parents
        )

        self.c_parents = QCheckBox(self.tab_relations)
        self.c_parents.setObjectName("c_parents")

        self.formLayout1.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.c_parents
        )

        self.main_tab.addTab(self.tab_relations, "")
        self.tab_info = QWidget()
        self.tab_info.setObjectName("tab_info")
        self.formLayout2 = QFormLayout(self.tab_info)
        self.formLayout2.setObjectName("formLayout2")
        self.lbl_id = QLabel(self.tab_info)
        self.lbl_id.setObjectName("lbl_id")

        self.formLayout2.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_id
        )

        self.c_id = QSpinBox(self.tab_info)
        self.c_id.setObjectName("c_id")

        self.formLayout2.setWidget(0, QFormLayout.ItemRole.FieldRole, self.c_id)

        self.main_tab.addTab(self.tab_info, "")

        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtTagEditor)

        self.main_tab.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(QtTagEditor)

    # setupUi

    def retranslate_ui(self, QtTagEditor):
        QtTagEditor.setWindowTitle(
            QCoreApplication.translate("QtTagEditor", "Tag Editor", None)
        )
        self.lbl_name.setText(
            QCoreApplication.translate("QtTagEditor", "Name ", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            QCoreApplication.translate("QtTagEditor", "General", None),
        )
        self.lbl_parents.setText(
            QCoreApplication.translate("QtTagEditor", "Parents ", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_relations),
            QCoreApplication.translate("QtTagEditor", "Relations", None),
        )
        self.lbl_id.setText(
            QCoreApplication.translate("QtTagEditor", "Id ", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_info),
            QCoreApplication.translate("QtTagEditor", "Info", None),
        )

    # retranslate_ui

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_id,
            self.c_name,
            self.c_parents,
            self.main_tab,
            self.tab_general,
            self.tab_info,
            self.tab_relations,
        ]
