from PyQt5 import QtCore, QtWidgets


class Ui_QtTagEditor:
    """Autogenerated content.

    Attributes:
        verticalLayout: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        formLayout: The layout for the widget.
        c_name: C name.
        tab_relations: Tab relations.
        formLayout1: The layout for the widget.
        c_parents: C parents.
        tab_info: Tab info.
        formLayout2: The layout for the widget.
        c_id: C id.

    """

    verticalLayout: "QtWidgets.QVBoxLayout"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    formLayout: "QtWidgets.QFormLayout"
    lbl_name: "QtWidgets.QLabel"
    c_name: "QtWidgets.QLineEdit"
    tab_relations: "QtWidgets.QWidget"
    formLayout1: "QtWidgets.QFormLayout"
    lbl_parents: "QtWidgets.QLabel"
    c_parents: "QtWidgets.QCheckBox"
    tab_info: "QtWidgets.QWidget"
    formLayout2: "QtWidgets.QFormLayout"
    lbl_id: "QtWidgets.QLabel"
    c_id: "QtWidgets.QSpinBox"

    def setup_ui(self, QtTagEditor):

        QtTagEditor.setObjectName("QtTagEditor")
        QtTagEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(QtTagEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(QtTagEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_name = QtWidgets.QLabel(self.tab_general)
        self.lbl_name.setObjectName("lbl_name")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_name
        )
        self.c_name = QtWidgets.QLineEdit(self.tab_general)
        self.c_name.setObjectName("c_name")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_name
        )
        self.main_tab.addTab(self.tab_general, "")
        self.tab_relations = QtWidgets.QWidget()
        self.tab_relations.setObjectName("tab_relations")
        self.formLayout1 = QtWidgets.QFormLayout(self.tab_relations)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_parents = QtWidgets.QLabel(self.tab_relations)
        self.lbl_parents.setObjectName("lbl_parents")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_parents
        )
        self.c_parents = QtWidgets.QCheckBox(self.tab_relations)
        self.c_parents.setObjectName("c_parents")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_parents
        )
        self.main_tab.addTab(self.tab_relations, "")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setObjectName("tab_info")
        self.formLayout2 = QtWidgets.QFormLayout(self.tab_info)
        self.formLayout2.setObjectName("formLayout2")
        self.lbl_id = QtWidgets.QLabel(self.tab_info)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_id
        )
        self.c_id = QtWidgets.QSpinBox(self.tab_info)
        self.c_id.setObjectName("c_id")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_id
        )
        self.main_tab.addTab(self.tab_info, "")
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtTagEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtTagEditor)

    def retranslate_ui(self, QtTagEditor):
        _translate = QtCore.QCoreApplication.translate
        QtTagEditor.setWindowTitle(_translate("QtTagEditor", "Tag Editor"))
        self.lbl_name.setText(_translate("QtTagEditor", "Name "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            _translate("QtTagEditor", "General"),
        )
        self.lbl_parents.setText(_translate("QtTagEditor", "Parents "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_relations),
            _translate("QtTagEditor", "Relations"),
        )
        self.lbl_id.setText(_translate("QtTagEditor", "Id "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_info),
            _translate("QtTagEditor", "Info"),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.main_tab,
            self.tab_general,
            self.c_name,
            self.tab_relations,
            self.c_parents,
            self.tab_info,
            self.c_id,
        ]
