from typing import Any

from PyQt6 import QtCore, QtWidgets


class Ui_QtTagEditor:
    """Autogenerated content.

    Attributes:
        c_id: C id.
        c_name: C name.
        c_parents: C parents.
        formLayout: The layout for the widget.
        formLayout1: The layout for the widget.
        formLayout2: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        tab_info: Tab info.
        tab_relations: Tab relations.
        verticalLayout: The layout for the widget.

    """

    c_id: "QtWidgets.QSpinBox"
    c_name: "QtWidgets.QLineEdit"
    c_parents: "QtWidgets.QCheckBox"
    formLayout: "QtWidgets.QFormLayout"
    formLayout1: "QtWidgets.QFormLayout"
    formLayout2: "QtWidgets.QFormLayout"
    lbl_id: "QtWidgets.QLabel"
    lbl_name: "QtWidgets.QLabel"
    lbl_parents: "QtWidgets.QLabel"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    tab_info: "QtWidgets.QWidget"
    tab_relations: "QtWidgets.QWidget"
    verticalLayout: "QtWidgets.QVBoxLayout"
    ctx: "Any"  # Injected by host widget when used as mixin

    def setup_ui(self, QtTagEditor):

        QtTagEditor.setObjectName("QtTagEditor")
        QtTagEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(QtTagEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(parent=QtTagEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_name = QtWidgets.QLabel(parent=self.tab_general)
        self.lbl_name.setObjectName("lbl_name")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_name
        )
        self.c_name = QtWidgets.QLineEdit(parent=self.tab_general)
        self.c_name.setObjectName("c_name")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.c_name
        )
        self.main_tab.addTab(self.tab_general, "")
        self.tab_relations = QtWidgets.QWidget()
        self.tab_relations.setObjectName("tab_relations")
        self.formLayout1 = QtWidgets.QFormLayout(self.tab_relations)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_parents = QtWidgets.QLabel(parent=self.tab_relations)
        self.lbl_parents.setObjectName("lbl_parents")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_parents
        )
        self.c_parents = QtWidgets.QCheckBox(parent=self.tab_relations)
        self.c_parents.setObjectName("c_parents")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.c_parents
        )
        self.main_tab.addTab(self.tab_relations, "")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setObjectName("tab_info")
        self.formLayout2 = QtWidgets.QFormLayout(self.tab_info)
        self.formLayout2.setObjectName("formLayout2")
        self.lbl_id = QtWidgets.QLabel(parent=self.tab_info)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_id
        )
        self.c_id = QtWidgets.QSpinBox(parent=self.tab_info)
        self.c_id.setObjectName("c_id")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.c_id
        )
        self.main_tab.addTab(self.tab_info, "")
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtTagEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtTagEditor)

    def retranslate_ui(self, QtTagEditor):
        QtTagEditor.setWindowTitle(
            self.ctx.t("gui.qt_tag_editor.window_title", "Tag Editor")
        )
        self.lbl_name.setText(self.ctx.t("gui.qt_tag_editor.lbl_name", "Name "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            self.ctx.t("gui.qt_tag_editor.tab_general", "General"),
        )
        self.lbl_parents.setText(
            self.ctx.t("gui.qt_tag_editor.lbl_parents", "Parents ")
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_relations),
            self.ctx.t("gui.qt_tag_editor.tab_relations", "Relations"),
        )
        self.lbl_id.setText(self.ctx.t("gui.qt_tag_editor.lbl_id", "Id "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_info),
            self.ctx.t("gui.qt_tag_editor.tab_info", "Info"),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_id,
            self.c_name,
            self.c_parents,
            self.main_tab,
            self.tab_general,
            self.tab_info,
            self.tab_relations,
        ]
