class Ui_QtParentTagAssociationEditor:
    """Autogenerated content.

    Attributes:
        c_parent_id: C parent id.
        c_tag_id: C tag id.
        formLayout: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        verticalLayout: The layout for the widget.

    """

    c_parent_id: "QSpinBox"
    c_tag_id: "QSpinBox"
    formLayout: "QFormLayout"
    lbl_parent_id: "QLabel"
    lbl_tag_id: "QLabel"
    main_tab: "QTabWidget"
    tab_general: "QWidget"
    verticalLayout: "QVBoxLayout"

    def setup_ui(self, QtParentTagAssociationEditor):

        if not QtParentTagAssociationEditor.objectName():
            QtParentTagAssociationEditor.setObjectName(
                "QtParentTagAssociationEditor"
            )
        QtParentTagAssociationEditor.resize(480, 640)
        self.verticalLayout = QVBoxLayout(QtParentTagAssociationEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QTabWidget(QtParentTagAssociationEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_parent_id = QLabel(self.tab_general)
        self.lbl_parent_id.setObjectName("lbl_parent_id")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_parent_id
        )

        self.c_parent_id = QSpinBox(self.tab_general)
        self.c_parent_id.setObjectName("c_parent_id")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.c_parent_id
        )

        self.lbl_tag_id = QLabel(self.tab_general)
        self.lbl_tag_id.setObjectName("lbl_tag_id")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.LabelRole, self.lbl_tag_id
        )

        self.c_tag_id = QSpinBox(self.tab_general)
        self.c_tag_id.setObjectName("c_tag_id")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.FieldRole, self.c_tag_id
        )

        self.main_tab.addTab(self.tab_general, "")

        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtParentTagAssociationEditor)

        self.main_tab.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(QtParentTagAssociationEditor)

    # setupUi

    def retranslate_ui(self, QtParentTagAssociationEditor):
        QtParentTagAssociationEditor.setWindowTitle(
            QCoreApplication.translate(
                "QtParentTagAssociationEditor",
                "ParentTagAssociation Editor",
                None,
            )
        )
        self.lbl_parent_id.setText(
            QCoreApplication.translate(
                "QtParentTagAssociationEditor", "Parent Id ", None
            )
        )
        self.lbl_tag_id.setText(
            QCoreApplication.translate(
                "QtParentTagAssociationEditor", "Tag Id ", None
            )
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            QCoreApplication.translate(
                "QtParentTagAssociationEditor", "General", None
            ),
        )

    # retranslate_ui

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_parent_id,
            self.c_tag_id,
            self.main_tab,
            self.tab_general,
        ]
