from PyQt5 import QtCore, QtWidgets


class Ui_QtParentTagAssociationEditor:
    """Autogenerated content.

    Attributes:
        verticalLayout: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        formLayout: The layout for the widget.
        c_parent_id: C parent id.
        c_tag_id: C tag id.

    """

    verticalLayout: "QtWidgets.QVBoxLayout"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    formLayout: "QtWidgets.QFormLayout"
    lbl_parent_id: "QtWidgets.QLabel"
    c_parent_id: "QtWidgets.QSpinBox"
    lbl_tag_id: "QtWidgets.QLabel"
    c_tag_id: "QtWidgets.QSpinBox"

    def setup_ui(self, QtParentTagAssociationEditor):

        QtParentTagAssociationEditor.setObjectName(
            "QtParentTagAssociationEditor"
        )
        QtParentTagAssociationEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(
            QtParentTagAssociationEditor
        )
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(QtParentTagAssociationEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_parent_id = QtWidgets.QLabel(self.tab_general)
        self.lbl_parent_id.setObjectName("lbl_parent_id")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_parent_id
        )
        self.c_parent_id = QtWidgets.QSpinBox(self.tab_general)
        self.c_parent_id.setObjectName("c_parent_id")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_parent_id
        )
        self.lbl_tag_id = QtWidgets.QLabel(self.tab_general)
        self.lbl_tag_id.setObjectName("lbl_tag_id")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.lbl_tag_id
        )
        self.c_tag_id = QtWidgets.QSpinBox(self.tab_general)
        self.c_tag_id.setObjectName("c_tag_id")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.c_tag_id
        )
        self.main_tab.addTab(self.tab_general, "")
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtParentTagAssociationEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtParentTagAssociationEditor)

    def retranslate_ui(self, QtParentTagAssociationEditor):
        _translate = QtCore.QCoreApplication.translate
        QtParentTagAssociationEditor.setWindowTitle(
            _translate(
                "QtParentTagAssociationEditor", "ParentTagAssociation Editor"
            )
        )
        self.lbl_parent_id.setText(
            _translate("QtParentTagAssociationEditor", "Parent Id ")
        )
        self.lbl_tag_id.setText(
            _translate("QtParentTagAssociationEditor", "Tag Id ")
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            _translate("QtParentTagAssociationEditor", "General"),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.main_tab,
            self.tab_general,
            self.c_parent_id,
            self.c_tag_id,
        ]
