class Ui_QtCompositeKeyModelEditor:
    """Autogenerated content.

    Attributes:
        c_description: C description.
        c_key_part1: C key part1.
        c_key_part2: C key part2.
        c_related_items: C related items.
        c_some_binary: C some binary.
        c_some_date: C some date.
        c_some_enum: C some enum.
        c_some_float: C some float.
        c_some_json: C some json.
        formLayout: The layout for the widget.
        formLayout1: The layout for the widget.
        formLayout2: The layout for the widget.
        main_tab: Main tab.
        tab_comments: Tab comments.
        tab_general: Tab general.
        tab_relations: Tab relations.
        verticalLayout: The layout for the widget.

    """

    c_description: "QLineEdit"
    c_key_part1: "QLineEdit"
    c_key_part2: "QSpinBox"
    c_related_items: "QCheckBox"
    c_some_binary: "QCheckBox"
    c_some_date: "QDateEdit"
    c_some_enum: "QLineEdit"
    c_some_float: "QDoubleSpinBox"
    c_some_json: "QCheckBox"
    formLayout: "QFormLayout"
    formLayout1: "QFormLayout"
    formLayout2: "QFormLayout"
    lbl_description: "QLabel"
    lbl_key_part1: "QLabel"
    lbl_key_part2: "QLabel"
    lbl_related_items: "QLabel"
    lbl_some_binary: "QLabel"
    lbl_some_date: "QLabel"
    lbl_some_enum: "QLabel"
    lbl_some_float: "QLabel"
    lbl_some_json: "QLabel"
    lbl_some_time: "QLabel"
    main_tab: "QTabWidget"
    tab_comments: "QWidget"
    tab_general: "QWidget"
    tab_relations: "QWidget"
    verticalLayout: "QVBoxLayout"

    def setup_ui(self, QtCompositeKeyModelEditor):

        if not QtCompositeKeyModelEditor.objectName():
            QtCompositeKeyModelEditor.setObjectName("QtCompositeKeyModelEditor")
        QtCompositeKeyModelEditor.resize(480, 640)
        self.verticalLayout = QVBoxLayout(QtCompositeKeyModelEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QTabWidget(QtCompositeKeyModelEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_key_part1 = QLabel(self.tab_general)
        self.lbl_key_part1.setObjectName("lbl_key_part1")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_key_part1
        )

        self.c_key_part1 = QLineEdit(self.tab_general)
        self.c_key_part1.setObjectName("c_key_part1")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.c_key_part1
        )

        self.lbl_key_part2 = QLabel(self.tab_general)
        self.lbl_key_part2.setObjectName("lbl_key_part2")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.LabelRole, self.lbl_key_part2
        )

        self.c_key_part2 = QSpinBox(self.tab_general)
        self.c_key_part2.setObjectName("c_key_part2")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.FieldRole, self.c_key_part2
        )

        self.lbl_some_binary = QLabel(self.tab_general)
        self.lbl_some_binary.setObjectName("lbl_some_binary")

        self.formLayout.setWidget(
            2, QFormLayout.ItemRole.LabelRole, self.lbl_some_binary
        )

        self.c_some_binary = QCheckBox(self.tab_general)
        self.c_some_binary.setObjectName("c_some_binary")

        self.formLayout.setWidget(
            2, QFormLayout.ItemRole.FieldRole, self.c_some_binary
        )

        self.lbl_some_date = QLabel(self.tab_general)
        self.lbl_some_date.setObjectName("lbl_some_date")

        self.formLayout.setWidget(
            3, QFormLayout.ItemRole.LabelRole, self.lbl_some_date
        )

        self.c_some_date = QDateEdit(self.tab_general)
        self.c_some_date.setObjectName("c_some_date")

        self.formLayout.setWidget(
            3, QFormLayout.ItemRole.FieldRole, self.c_some_date
        )

        self.lbl_some_enum = QLabel(self.tab_general)
        self.lbl_some_enum.setObjectName("lbl_some_enum")

        self.formLayout.setWidget(
            4, QFormLayout.ItemRole.LabelRole, self.lbl_some_enum
        )

        self.c_some_enum = QLineEdit(self.tab_general)
        self.c_some_enum.setObjectName("c_some_enum")

        self.formLayout.setWidget(
            4, QFormLayout.ItemRole.FieldRole, self.c_some_enum
        )

        self.lbl_some_float = QLabel(self.tab_general)
        self.lbl_some_float.setObjectName("lbl_some_float")

        self.formLayout.setWidget(
            5, QFormLayout.ItemRole.LabelRole, self.lbl_some_float
        )

        self.c_some_float = QDoubleSpinBox(self.tab_general)
        self.c_some_float.setObjectName("c_some_float")

        self.formLayout.setWidget(
            5, QFormLayout.ItemRole.FieldRole, self.c_some_float
        )

        self.lbl_some_json = QLabel(self.tab_general)
        self.lbl_some_json.setObjectName("lbl_some_json")

        self.formLayout.setWidget(
            6, QFormLayout.ItemRole.LabelRole, self.lbl_some_json
        )

        self.c_some_json = QCheckBox(self.tab_general)
        self.c_some_json.setObjectName("c_some_json")

        self.formLayout.setWidget(
            6, QFormLayout.ItemRole.FieldRole, self.c_some_json
        )

        self.lbl_some_time = QLabel(self.tab_general)
        self.lbl_some_time.setObjectName("lbl_some_time")

        self.formLayout.setWidget(
            7, QFormLayout.ItemRole.LabelRole, self.lbl_some_time
        )

        self.main_tab.addTab(self.tab_general, "")
        self.tab_relations = QWidget()
        self.tab_relations.setObjectName("tab_relations")
        self.formLayout1 = QFormLayout(self.tab_relations)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_related_items = QLabel(self.tab_relations)
        self.lbl_related_items.setObjectName("lbl_related_items")

        self.formLayout1.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_related_items
        )

        self.c_related_items = QCheckBox(self.tab_relations)
        self.c_related_items.setObjectName("c_related_items")

        self.formLayout1.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.c_related_items
        )

        self.main_tab.addTab(self.tab_relations, "")
        self.tab_comments = QWidget()
        self.tab_comments.setObjectName("tab_comments")
        self.formLayout2 = QFormLayout(self.tab_comments)
        self.formLayout2.setObjectName("formLayout2")
        self.lbl_description = QLabel(self.tab_comments)
        self.lbl_description.setObjectName("lbl_description")

        self.formLayout2.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_description
        )

        self.c_description = QLineEdit(self.tab_comments)
        self.c_description.setObjectName("c_description")

        self.formLayout2.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.c_description
        )

        self.main_tab.addTab(self.tab_comments, "")

        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtCompositeKeyModelEditor)

        self.main_tab.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(QtCompositeKeyModelEditor)

    # setupUi

    def retranslate_ui(self, QtCompositeKeyModelEditor):
        QtCompositeKeyModelEditor.setWindowTitle(
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "CompositeKeyModel Editor", None
            )
        )
        self.lbl_key_part1.setText(
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "Key Part1 ", None
            )
        )
        self.lbl_key_part2.setText(
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "Key Part2 ", None
            )
        )
        self.lbl_some_binary.setText(
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "Some Binary ", None
            )
        )
        self.lbl_some_date.setText(
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "Some Date ", None
            )
        )
        self.lbl_some_enum.setText(
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "Some Enum ", None
            )
        )
        self.lbl_some_float.setText(
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "Some Float ", None
            )
        )
        self.lbl_some_json.setText(
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "Some Json ", None
            )
        )
        self.lbl_some_time.setText(
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "Some Time ", None
            )
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "General", None
            ),
        )
        self.lbl_related_items.setText(
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "Related Items ", None
            )
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_relations),
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "Relations", None
            ),
        )
        self.lbl_description.setText(
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "Description ", None
            )
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_comments),
            QCoreApplication.translate(
                "QtCompositeKeyModelEditor", "Comments", None
            ),
        )

    # retranslate_ui

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_description,
            self.c_key_part1,
            self.c_key_part2,
            self.c_related_items,
            self.c_some_binary,
            self.c_some_date,
            self.c_some_enum,
            self.c_some_float,
            self.c_some_json,
            self.main_tab,
            self.tab_comments,
            self.tab_general,
            self.tab_relations,
        ]
