from PyQt5 import QtCore, QtWidgets


class Ui_QtCompositeKeyModelEditor:
    """Autogenerated content.

    Attributes:
        verticalLayout: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        formLayout: The layout for the widget.
        c_key_part1: C key part1.
        c_key_part2: C key part2.
        c_some_binary: C some binary.
        c_some_date: C some date.
        c_some_enum: C some enum.
        c_some_float: C some float.
        c_some_json: C some json.
        tab_relations: Tab relations.
        formLayout1: The layout for the widget.
        c_related_items: C related items.
        tab_comments: Tab comments.
        formLayout2: The layout for the widget.
        c_description: C description.

    """

    verticalLayout: "QtWidgets.QVBoxLayout"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    formLayout: "QtWidgets.QFormLayout"
    lbl_key_part1: "QtWidgets.QLabel"
    c_key_part1: "QtWidgets.QLineEdit"
    lbl_key_part2: "QtWidgets.QLabel"
    c_key_part2: "QtWidgets.QSpinBox"
    lbl_some_binary: "QtWidgets.QLabel"
    c_some_binary: "QtWidgets.QCheckBox"
    lbl_some_date: "QtWidgets.QLabel"
    c_some_date: "QtWidgets.QDateEdit"
    lbl_some_enum: "QtWidgets.QLabel"
    c_some_enum: "QtWidgets.QLineEdit"
    lbl_some_float: "QtWidgets.QLabel"
    c_some_float: "QtWidgets.QDoubleSpinBox"
    lbl_some_json: "QtWidgets.QLabel"
    c_some_json: "QtWidgets.QCheckBox"
    lbl_some_time: "QtWidgets.QLabel"
    tab_relations: "QtWidgets.QWidget"
    formLayout1: "QtWidgets.QFormLayout"
    lbl_related_items: "QtWidgets.QLabel"
    c_related_items: "QtWidgets.QCheckBox"
    tab_comments: "QtWidgets.QWidget"
    formLayout2: "QtWidgets.QFormLayout"
    lbl_description: "QtWidgets.QLabel"
    c_description: "QtWidgets.QLineEdit"

    def setup_ui(self, QtCompositeKeyModelEditor):

        QtCompositeKeyModelEditor.setObjectName("QtCompositeKeyModelEditor")
        QtCompositeKeyModelEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(QtCompositeKeyModelEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(QtCompositeKeyModelEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_key_part1 = QtWidgets.QLabel(self.tab_general)
        self.lbl_key_part1.setObjectName("lbl_key_part1")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_key_part1
        )
        self.c_key_part1 = QtWidgets.QLineEdit(self.tab_general)
        self.c_key_part1.setObjectName("c_key_part1")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_key_part1
        )
        self.lbl_key_part2 = QtWidgets.QLabel(self.tab_general)
        self.lbl_key_part2.setObjectName("lbl_key_part2")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.lbl_key_part2
        )
        self.c_key_part2 = QtWidgets.QSpinBox(self.tab_general)
        self.c_key_part2.setObjectName("c_key_part2")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.c_key_part2
        )
        self.lbl_some_binary = QtWidgets.QLabel(self.tab_general)
        self.lbl_some_binary.setObjectName("lbl_some_binary")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.lbl_some_binary
        )
        self.c_some_binary = QtWidgets.QCheckBox(self.tab_general)
        self.c_some_binary.setObjectName("c_some_binary")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.c_some_binary
        )
        self.lbl_some_date = QtWidgets.QLabel(self.tab_general)
        self.lbl_some_date.setObjectName("lbl_some_date")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.lbl_some_date
        )
        self.c_some_date = QtWidgets.QDateEdit(self.tab_general)
        self.c_some_date.setObjectName("c_some_date")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.c_some_date
        )
        self.lbl_some_enum = QtWidgets.QLabel(self.tab_general)
        self.lbl_some_enum.setObjectName("lbl_some_enum")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.lbl_some_enum
        )
        self.c_some_enum = QtWidgets.QLineEdit(self.tab_general)
        self.c_some_enum.setObjectName("c_some_enum")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.FieldRole, self.c_some_enum
        )
        self.lbl_some_float = QtWidgets.QLabel(self.tab_general)
        self.lbl_some_float.setObjectName("lbl_some_float")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.LabelRole, self.lbl_some_float
        )
        self.c_some_float = QtWidgets.QDoubleSpinBox(self.tab_general)
        self.c_some_float.setObjectName("c_some_float")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.FieldRole, self.c_some_float
        )
        self.lbl_some_json = QtWidgets.QLabel(self.tab_general)
        self.lbl_some_json.setObjectName("lbl_some_json")
        self.formLayout.setWidget(
            6, QtWidgets.QFormLayout.LabelRole, self.lbl_some_json
        )
        self.c_some_json = QtWidgets.QCheckBox(self.tab_general)
        self.c_some_json.setObjectName("c_some_json")
        self.formLayout.setWidget(
            6, QtWidgets.QFormLayout.FieldRole, self.c_some_json
        )
        self.lbl_some_time = QtWidgets.QLabel(self.tab_general)
        self.lbl_some_time.setObjectName("lbl_some_time")
        self.formLayout.setWidget(
            7, QtWidgets.QFormLayout.LabelRole, self.lbl_some_time
        )
        self.main_tab.addTab(self.tab_general, "")
        self.tab_relations = QtWidgets.QWidget()
        self.tab_relations.setObjectName("tab_relations")
        self.formLayout1 = QtWidgets.QFormLayout(self.tab_relations)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_related_items = QtWidgets.QLabel(self.tab_relations)
        self.lbl_related_items.setObjectName("lbl_related_items")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_related_items
        )
        self.c_related_items = QtWidgets.QCheckBox(self.tab_relations)
        self.c_related_items.setObjectName("c_related_items")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_related_items
        )
        self.main_tab.addTab(self.tab_relations, "")
        self.tab_comments = QtWidgets.QWidget()
        self.tab_comments.setObjectName("tab_comments")
        self.formLayout2 = QtWidgets.QFormLayout(self.tab_comments)
        self.formLayout2.setObjectName("formLayout2")
        self.lbl_description = QtWidgets.QLabel(self.tab_comments)
        self.lbl_description.setObjectName("lbl_description")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_description
        )
        self.c_description = QtWidgets.QLineEdit(self.tab_comments)
        self.c_description.setObjectName("c_description")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_description
        )
        self.main_tab.addTab(self.tab_comments, "")
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtCompositeKeyModelEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtCompositeKeyModelEditor)

    def retranslate_ui(self, QtCompositeKeyModelEditor):
        _translate = QtCore.QCoreApplication.translate
        QtCompositeKeyModelEditor.setWindowTitle(
            _translate("QtCompositeKeyModelEditor", "CompositeKeyModel Editor")
        )
        self.lbl_key_part1.setText(
            _translate("QtCompositeKeyModelEditor", "Key Part1 ")
        )
        self.lbl_key_part2.setText(
            _translate("QtCompositeKeyModelEditor", "Key Part2 ")
        )
        self.lbl_some_binary.setText(
            _translate("QtCompositeKeyModelEditor", "Some Binary ")
        )
        self.lbl_some_date.setText(
            _translate("QtCompositeKeyModelEditor", "Some Date ")
        )
        self.lbl_some_enum.setText(
            _translate("QtCompositeKeyModelEditor", "Some Enum ")
        )
        self.lbl_some_float.setText(
            _translate("QtCompositeKeyModelEditor", "Some Float ")
        )
        self.lbl_some_json.setText(
            _translate("QtCompositeKeyModelEditor", "Some Json ")
        )
        self.lbl_some_time.setText(
            _translate("QtCompositeKeyModelEditor", "Some Time ")
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            _translate("QtCompositeKeyModelEditor", "General"),
        )
        self.lbl_related_items.setText(
            _translate("QtCompositeKeyModelEditor", "Related Items ")
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_relations),
            _translate("QtCompositeKeyModelEditor", "Relations"),
        )
        self.lbl_description.setText(
            _translate("QtCompositeKeyModelEditor", "Description ")
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_comments),
            _translate("QtCompositeKeyModelEditor", "Comments"),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.main_tab,
            self.tab_general,
            self.c_key_part1,
            self.c_key_part2,
            self.c_some_binary,
            self.c_some_date,
            self.c_some_enum,
            self.c_some_float,
            self.c_some_json,
            self.tab_relations,
            self.c_related_items,
            self.tab_comments,
            self.c_description,
        ]
