from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from exdrf_qt.field_ed.api import DrfIntEditor, DrfTextEditor

    from exdrf_dev.qt_gen.db.parents.api import QtParentSiSe


class Ui_QtChildEditor:
    """Autogenerated content.

    Attributes:
        c_data: C data.
        c_id: C id.
        c_parent: C parent.
        formLayout: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        verticalLayout: The layout for the widget.

    """

    c_data: "DrfTextEditor"
    c_id: "DrfIntEditor"
    c_parent: "QtParentSiSe"
    formLayout: "QFormLayout"
    lbl_data: "QLabel"
    lbl_id: "QLabel"
    lbl_parent: "QLabel"
    main_tab: "QTabWidget"
    tab_general: "QWidget"
    verticalLayout: "QVBoxLayout"

    def setup_ui(self, QtChildEditor):
        from exdrf_qt.field_ed.api import DrfIntEditor, DrfTextEditor

        from exdrf_dev.qt_gen.db.parents.api import QtParentSiSe

        if not QtChildEditor.objectName():
            QtChildEditor.setObjectName("QtChildEditor")
        QtChildEditor.resize(480, 640)
        self.verticalLayout = QVBoxLayout(QtChildEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QTabWidget(QtChildEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_data = QLabel(self.tab_general)
        self.lbl_data.setObjectName("lbl_data")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_data
        )

        self.c_data = DrfTextEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_data.setObjectName("c_data")
        self.c_data.setProperty("name", "data")
        self.c_data.setProperty("clearable", True)

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.c_data
        )

        self.lbl_parent = QLabel(self.tab_general)
        self.lbl_parent.setObjectName("lbl_parent")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.LabelRole, self.lbl_parent
        )

        self.c_parent = QtParentSiSe(parent=self.tab_general, ctx=self.ctx)
        self.c_parent.setObjectName("c_parent")
        self.c_parent.setProperty("name", "parent")
        self.c_parent.setProperty("clearable", True)

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.FieldRole, self.c_parent
        )

        self.lbl_id = QLabel(self.tab_general)
        self.lbl_id.setObjectName("lbl_id")

        self.formLayout.setWidget(
            2, QFormLayout.ItemRole.LabelRole, self.lbl_id
        )

        self.c_id = DrfIntEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_id.setObjectName("c_id")
        self.c_id.setProperty("name", "id")

        self.formLayout.setWidget(2, QFormLayout.ItemRole.FieldRole, self.c_id)

        self.main_tab.addTab(self.tab_general, "")

        self.verticalLayout.addWidget(self.main_tab)

        self.lbl_data.setBuddy(self.c_data)
        self.lbl_parent.setBuddy(self.c_parent)
        self.lbl_id.setBuddy(self.c_id)

        self.retranslate_ui(QtChildEditor)

        self.main_tab.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(QtChildEditor)

    # setupUi

    def retranslate_ui(self, QtChildEditor):
        QtChildEditor.setWindowTitle(
            QCoreApplication.translate("QtChildEditor", "Child Editor", None)
        )
        self.lbl_data.setText(
            QCoreApplication.translate("QtChildEditor", "Data ", None)
        )
        self.lbl_parent.setText(
            QCoreApplication.translate("QtChildEditor", "Parent ", None)
        )
        self.lbl_id.setText(
            QCoreApplication.translate("QtChildEditor", "Id ", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            QCoreApplication.translate("QtChildEditor", "General", None),
        )

    # retranslate_ui

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_data,
            self.c_id,
            self.c_parent,
            self.main_tab,
            self.tab_general,
        ]
