from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from exdrf_qt.field_ed.api import (
        DrfIntEditor,
        DrfLineEditor,
        QtTagRelParent,
    )


class Ui_QtTagEditor:
    """Autogenerated content.

    Attributes:
        c_id: C id.
        c_name: C name.
        c_parents: C parents.
        formLayout: The layout for the widget.
        formLayout1: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        tab_parents_rel: Tab parents rel.
        verticalLayout: The layout for the widget.

    """

    c_id: "DrfIntEditor"
    c_name: "DrfLineEditor"
    c_parents: "QtTagRelParent"
    formLayout: "QFormLayout"
    formLayout1: "QVBoxLayout"
    lbl_id: "QLabel"
    lbl_name: "QLabel"
    main_tab: "QTabWidget"
    tab_general: "QWidget"
    tab_parents_rel: "QWidget"
    verticalLayout: "QVBoxLayout"

    def setup_ui(self, QtTagEditor):
        from exdrf_qt.field_ed.api import (
            DrfIntEditor,
            DrfLineEditor,
            QtTagRelParent,
        )

        if not QtTagEditor.objectName():
            QtTagEditor.setObjectName("QtTagEditor")
        QtTagEditor.resize(480, 640)
        self.verticalLayout = QVBoxLayout(QtTagEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QTabWidget(QtTagEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_name = QLabel(self.tab_general)
        self.lbl_name.setObjectName("lbl_name")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_name
        )

        self.c_name = DrfLineEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_name.setObjectName("c_name")
        self.c_name.setProperty("name", "name")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.c_name
        )

        self.lbl_id = QLabel(self.tab_general)
        self.lbl_id.setObjectName("lbl_id")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.LabelRole, self.lbl_id
        )

        self.c_id = DrfIntEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_id.setObjectName("c_id")
        self.c_id.setProperty("name", "id")

        self.formLayout.setWidget(1, QFormLayout.ItemRole.FieldRole, self.c_id)

        self.main_tab.addTab(self.tab_general, "")
        self.tab_parents_rel = QWidget()
        self.tab_parents_rel.setObjectName("tab_parents_rel")
        self.formLayout1 = QVBoxLayout(self.tab_parents_rel)
        self.formLayout1.setObjectName("formLayout1")
        self.c_parents = QtTagRelParent(
            parent=self.tab_parents_rel, ctx=self.ctx
        )
        self.c_parents.setObjectName("c_parents")
        self.c_parents.setProperty("name", "parents")

        self.formLayout1.addWidget(self.c_parents)

        self.main_tab.addTab(self.tab_parents_rel, "")

        self.verticalLayout.addWidget(self.main_tab)

        self.lbl_name.setBuddy(self.c_name)
        self.lbl_id.setBuddy(self.c_id)

        self.retranslate_ui(QtTagEditor)

        self.main_tab.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(QtTagEditor)

    # setupUi

    def retranslate_ui(self, QtTagEditor):
        QtTagEditor.setWindowTitle(
            QCoreApplication.translate("QtTagEditor", "Tag Editor", None)
        )
        self.lbl_name.setText(
            QCoreApplication.translate("QtTagEditor", "Name ", None)
        )
        self.lbl_id.setText(
            QCoreApplication.translate("QtTagEditor", "Id ", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            QCoreApplication.translate("QtTagEditor", "General", None),
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_parents_rel),
            QCoreApplication.translate("QtTagEditor", "Parents", None),
        )

    # retranslate_ui

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_id,
            self.c_name,
            self.c_parents,
            self.main_tab,
            self.tab_general,
            self.tab_parents_rel,
        ]
