from typing import TYPE_CHECKING

from PyQt5 import QtCore, QtWidgets

if TYPE_CHECKING:
    from exdrf_qt.field_ed.api import DrfIntEditor, DrfLineEditor, QtParentMuSe


class Ui_QtTagEditor:
    """Autogenerated content.

    Attributes:
        verticalLayout: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        formLayout: The layout for the widget.
        c_id: C id.
        c_name: C name.
        c_parents: C parents.

    """

    verticalLayout: "QtWidgets.QVBoxLayout"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    formLayout: "QtWidgets.QFormLayout"
    lbl_id: "QtWidgets.QLabel"
    c_id: "DrfIntEditor"
    lbl_name: "QtWidgets.QLabel"
    c_name: "DrfLineEditor"
    lbl_parents: "QtWidgets.QLabel"
    c_parents: "QtParentMuSe"

    def setup_ui(self, QtTagEditor):
        from exdrf_qt.field_ed.api import (
            DrfIntEditor,
            DrfLineEditor,
            QtParentMuSe,
        )

        QtTagEditor.setObjectName("QtTagEditor")
        QtTagEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(QtTagEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(QtTagEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_id = QtWidgets.QLabel(self.tab_general)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_id
        )
        self.c_id = DrfIntEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_id.setObjectName("c_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.c_id)
        self.lbl_name = QtWidgets.QLabel(self.tab_general)
        self.lbl_name.setObjectName("lbl_name")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.lbl_name
        )
        self.c_name = DrfLineEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_name.setObjectName("c_name")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.c_name
        )
        self.lbl_parents = QtWidgets.QLabel(self.tab_general)
        self.lbl_parents.setObjectName("lbl_parents")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.lbl_parents
        )
        self.c_parents = QtParentMuSe(parent=self.tab_general, ctx=self.ctx)
        self.c_parents.setObjectName("c_parents")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.c_parents
        )
        self.main_tab.addTab(self.tab_general, "")
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtTagEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtTagEditor)

    def retranslate_ui(self, QtTagEditor):
        _translate = QtCore.QCoreApplication.translate
        QtTagEditor.setWindowTitle(_translate("QtTagEditor", "Tag Editor"))
        self.lbl_id.setText(_translate("QtTagEditor", "Id "))
        self.lbl_name.setText(_translate("QtTagEditor", "Name "))
        self.lbl_parents.setText(_translate("QtTagEditor", "Parents "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            _translate("QtTagEditor", "General"),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.main_tab,
            self.tab_general,
            self.c_id,
            self.c_name,
            self.c_parents,
        ]
