from typing import TYPE_CHECKING, Any

from PyQt6 import QtCore, QtWidgets

if TYPE_CHECKING:
    from exdrf_qt.field_ed.api import DrfIntEditor


class Ui_QtParentTagAssociationEditor:
    """Autogenerated content.

    Attributes:
        c_parent_id: C parent id.
        c_tag_id: C tag id.
        formLayout: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        verticalLayout: The layout for the widget.

    """

    c_parent_id: "DrfIntEditor"
    c_tag_id: "DrfIntEditor"
    formLayout: "QtWidgets.QFormLayout"
    lbl_parent_id: "QtWidgets.QLabel"
    lbl_tag_id: "QtWidgets.QLabel"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    verticalLayout: "QtWidgets.QVBoxLayout"
    ctx: "Any"  # Injected by host widget when used as mixin

    def setup_ui(self, QtParentTagAssociationEditor):
        from exdrf_qt.field_ed.api import DrfIntEditor

        QtParentTagAssociationEditor.setObjectName(
            "QtParentTagAssociationEditor"
        )
        QtParentTagAssociationEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(
            QtParentTagAssociationEditor
        )
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(
            parent=QtParentTagAssociationEditor
        )
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_parent_id = QtWidgets.QLabel(parent=self.tab_general)
        self.lbl_parent_id.setObjectName("lbl_parent_id")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_parent_id
        )
        self.c_parent_id = DrfIntEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_parent_id.setProperty("name", "parent_id")
        self.c_parent_id.setObjectName("c_parent_id")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.c_parent_id
        )
        self.lbl_tag_id = QtWidgets.QLabel(parent=self.tab_general)
        self.lbl_tag_id.setObjectName("lbl_tag_id")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_tag_id
        )
        self.c_tag_id = DrfIntEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_tag_id.setProperty("name", "tag_id")
        self.c_tag_id.setObjectName("c_tag_id")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.c_tag_id
        )
        self.main_tab.addTab(self.tab_general, "")
        self.verticalLayout.addWidget(self.main_tab)
        self.lbl_parent_id.setBuddy(self.c_parent_id)
        self.lbl_tag_id.setBuddy(self.c_tag_id)

        self.retranslate_ui(QtParentTagAssociationEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtParentTagAssociationEditor)

    def retranslate_ui(self, QtParentTagAssociationEditor):
        QtParentTagAssociationEditor.setWindowTitle(
            self.ctx.t(
                "gui.qt_parent_tag_association_editor.window_title",
                "Parent tag association Editor",
            )
        )
        self.lbl_parent_id.setText(
            self.ctx.t(
                "gui.qt_parent_tag_association_editor.lbl_parent_id",
                "Parent Id ",
            )
        )
        self.lbl_tag_id.setText(
            self.ctx.t(
                "gui.qt_parent_tag_association_editor.lbl_tag_id", "Tag Id "
            )
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            self.ctx.t(
                "gui.qt_parent_tag_association_editor.tab_general", "General"
            ),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_parent_id,
            self.c_tag_id,
            self.main_tab,
            self.tab_general,
        ]
