from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow:
    """Autogenerated content.

    Attributes:
        central_widget: Central widget.
        verticalLayout: The layout for the widget.
        mdi_area: Mdi area.
        menubar: Menubar.
        menu_file: Menu file.
        menu_concerns: Menu concerns.
        statusbar: Statusbar.

    """

    central_widget: "QtWidgets.QWidget"
    verticalLayout: "QtWidgets.QVBoxLayout"
    mdi_area: "QtWidgets.QMdiArea"
    menubar: "QtWidgets.QMenuBar"
    menu_file: "QtWidgets.QMenu"
    menu_concerns: "QtWidgets.QMenu"
    statusbar: "QtWidgets.QStatusBar"

    def setup_ui(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 592)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mdi_area = QtWidgets.QMdiArea(self.central_widget)
        self.mdi_area.setObjectName("mdi_area")
        self.verticalLayout.addWidget(self.mdi_area)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_concerns = QtWidgets.QMenu(self.menubar)
        self.menu_concerns.setObjectName("menu_concerns")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_concerns.menuAction())

        self.retranslate_ui(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslate_ui(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_file.setTitle(_translate("MainWindow", "File"))
        self.menu_concerns.setTitle(_translate("MainWindow", "Concerns"))

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.central_widget,
            self.mdi_area,
            self.menubar,
            self.menu_file,
            self.menu_concerns,
            self.statusbar,
        ]
