class Ui_MainWindow:
    """Autogenerated content.

    Attributes:
        central_widget: Central widget.
        mdi_area: Mdi area.
        menu_concerns: Menu concerns.
        menu_file: Menu file.
        menubar: Menubar.
        statusbar: Statusbar.
        verticalLayout: The layout for the widget.

    """

    central_widget: "QWidget"
    mdi_area: "QMdiArea"
    menu_concerns: "QMenu"
    menu_file: "QMenu"
    menubar: "QMenuBar"
    statusbar: "QStatusBar"
    verticalLayout: "QVBoxLayout"

    def setup_ui(self, MainWindow):

        if not MainWindow.objectName():
            MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 592)
        self.central_widget = QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mdi_area = QMdiArea(self.central_widget)
        self.mdi_area.setObjectName("mdi_area")

        self.verticalLayout.addWidget(self.mdi_area)

        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        self.menubar.setGeometry(QRect(0, 0, 640, 21))
        self.menu_file = QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_concerns = QMenu(self.menubar)
        self.menu_concerns.setObjectName("menu_concerns")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_concerns.menuAction())

        self.retranslate_ui(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    # setupUi

    def retranslate_ui(self, MainWindow):
        MainWindow.setWindowTitle(
            QCoreApplication.translate("MainWindow", "MainWindow", None)
        )
        self.menu_file.setTitle(
            QCoreApplication.translate("MainWindow", "File", None)
        )
        self.menu_concerns.setTitle(
            QCoreApplication.translate("MainWindow", "Concerns", None)
        )

    # retranslate_ui

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.central_widget,
            self.mdi_area,
            self.menu_concerns,
            self.menu_file,
            self.menubar,
            self.statusbar,
        ]
