class Ui_QtProfileEditor:
    """Autogenerated content.

    Attributes:
        c_bio: C bio.
        c_id: C id.
        c_parent: C parent.
        c_parent_id: C parent id.
        formLayout: The layout for the widget.
        formLayout1: The layout for the widget.
        formLayout2: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        tab_info: Tab info.
        tab_relations: Tab relations.
        verticalLayout: The layout for the widget.

    """

    c_bio: "QLineEdit"
    c_id: "QSpinBox"
    c_parent: "QCheckBox"
    c_parent_id: "QSpinBox"
    formLayout: "QFormLayout"
    formLayout1: "QFormLayout"
    formLayout2: "QFormLayout"
    lbl_bio: "QLabel"
    lbl_id: "QLabel"
    lbl_parent: "QLabel"
    lbl_parent_id: "QLabel"
    main_tab: "QTabWidget"
    tab_general: "QWidget"
    tab_info: "QWidget"
    tab_relations: "QWidget"
    verticalLayout: "QVBoxLayout"

    def setup_ui(self, QtProfileEditor):

        if not QtProfileEditor.objectName():
            QtProfileEditor.setObjectName("QtProfileEditor")
        QtProfileEditor.resize(480, 640)
        self.verticalLayout = QVBoxLayout(QtProfileEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QTabWidget(QtProfileEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_bio = QLabel(self.tab_general)
        self.lbl_bio.setObjectName("lbl_bio")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_bio
        )

        self.c_bio = QLineEdit(self.tab_general)
        self.c_bio.setObjectName("c_bio")

        self.formLayout.setWidget(0, QFormLayout.ItemRole.FieldRole, self.c_bio)

        self.lbl_parent_id = QLabel(self.tab_general)
        self.lbl_parent_id.setObjectName("lbl_parent_id")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.LabelRole, self.lbl_parent_id
        )

        self.c_parent_id = QSpinBox(self.tab_general)
        self.c_parent_id.setObjectName("c_parent_id")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.FieldRole, self.c_parent_id
        )

        self.main_tab.addTab(self.tab_general, "")
        self.tab_relations = QWidget()
        self.tab_relations.setObjectName("tab_relations")
        self.formLayout1 = QFormLayout(self.tab_relations)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_parent = QLabel(self.tab_relations)
        self.lbl_parent.setObjectName("lbl_parent")

        self.formLayout1.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_parent
        )

        self.c_parent = QCheckBox(self.tab_relations)
        self.c_parent.setObjectName("c_parent")

        self.formLayout1.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.c_parent
        )

        self.main_tab.addTab(self.tab_relations, "")
        self.tab_info = QWidget()
        self.tab_info.setObjectName("tab_info")
        self.formLayout2 = QFormLayout(self.tab_info)
        self.formLayout2.setObjectName("formLayout2")
        self.lbl_id = QLabel(self.tab_info)
        self.lbl_id.setObjectName("lbl_id")

        self.formLayout2.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_id
        )

        self.c_id = QSpinBox(self.tab_info)
        self.c_id.setObjectName("c_id")

        self.formLayout2.setWidget(0, QFormLayout.ItemRole.FieldRole, self.c_id)

        self.main_tab.addTab(self.tab_info, "")

        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtProfileEditor)

        self.main_tab.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(QtProfileEditor)

    # setupUi

    def retranslate_ui(self, QtProfileEditor):
        QtProfileEditor.setWindowTitle(
            QCoreApplication.translate(
                "QtProfileEditor", "Profile Editor", None
            )
        )
        self.lbl_bio.setText(
            QCoreApplication.translate("QtProfileEditor", "Bio ", None)
        )
        self.lbl_parent_id.setText(
            QCoreApplication.translate("QtProfileEditor", "Parent Id ", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            QCoreApplication.translate("QtProfileEditor", "General", None),
        )
        self.lbl_parent.setText(
            QCoreApplication.translate("QtProfileEditor", "Parent ", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_relations),
            QCoreApplication.translate("QtProfileEditor", "Relations", None),
        )
        self.lbl_id.setText(
            QCoreApplication.translate("QtProfileEditor", "Id ", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_info),
            QCoreApplication.translate("QtProfileEditor", "Info", None),
        )

    # retranslate_ui

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_bio,
            self.c_id,
            self.c_parent,
            self.c_parent_id,
            self.main_tab,
            self.tab_general,
            self.tab_info,
            self.tab_relations,
        ]
