from PyQt5 import QtCore, QtWidgets


class Ui_QtProfileEditor:
    """Autogenerated content.

    Attributes:
        verticalLayout: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        formLayout: The layout for the widget.
        c_bio: C bio.
        c_parent_id: C parent id.
        tab_relations: Tab relations.
        formLayout1: The layout for the widget.
        c_parent: C parent.
        tab_info: Tab info.
        formLayout2: The layout for the widget.
        c_id: C id.

    """

    verticalLayout: "QtWidgets.QVBoxLayout"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    formLayout: "QtWidgets.QFormLayout"
    lbl_bio: "QtWidgets.QLabel"
    c_bio: "QtWidgets.QLineEdit"
    lbl_parent_id: "QtWidgets.QLabel"
    c_parent_id: "QtWidgets.QSpinBox"
    tab_relations: "QtWidgets.QWidget"
    formLayout1: "QtWidgets.QFormLayout"
    lbl_parent: "QtWidgets.QLabel"
    c_parent: "QtWidgets.QCheckBox"
    tab_info: "QtWidgets.QWidget"
    formLayout2: "QtWidgets.QFormLayout"
    lbl_id: "QtWidgets.QLabel"
    c_id: "QtWidgets.QSpinBox"

    def setup_ui(self, QtProfileEditor):

        QtProfileEditor.setObjectName("QtProfileEditor")
        QtProfileEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(QtProfileEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(QtProfileEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_bio = QtWidgets.QLabel(self.tab_general)
        self.lbl_bio.setObjectName("lbl_bio")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_bio
        )
        self.c_bio = QtWidgets.QLineEdit(self.tab_general)
        self.c_bio.setObjectName("c_bio")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_bio
        )
        self.lbl_parent_id = QtWidgets.QLabel(self.tab_general)
        self.lbl_parent_id.setObjectName("lbl_parent_id")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.lbl_parent_id
        )
        self.c_parent_id = QtWidgets.QSpinBox(self.tab_general)
        self.c_parent_id.setObjectName("c_parent_id")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.c_parent_id
        )
        self.main_tab.addTab(self.tab_general, "")
        self.tab_relations = QtWidgets.QWidget()
        self.tab_relations.setObjectName("tab_relations")
        self.formLayout1 = QtWidgets.QFormLayout(self.tab_relations)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_parent = QtWidgets.QLabel(self.tab_relations)
        self.lbl_parent.setObjectName("lbl_parent")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_parent
        )
        self.c_parent = QtWidgets.QCheckBox(self.tab_relations)
        self.c_parent.setObjectName("c_parent")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_parent
        )
        self.main_tab.addTab(self.tab_relations, "")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setObjectName("tab_info")
        self.formLayout2 = QtWidgets.QFormLayout(self.tab_info)
        self.formLayout2.setObjectName("formLayout2")
        self.lbl_id = QtWidgets.QLabel(self.tab_info)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_id
        )
        self.c_id = QtWidgets.QSpinBox(self.tab_info)
        self.c_id.setObjectName("c_id")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_id
        )
        self.main_tab.addTab(self.tab_info, "")
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtProfileEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtProfileEditor)

    def retranslate_ui(self, QtProfileEditor):
        _translate = QtCore.QCoreApplication.translate
        QtProfileEditor.setWindowTitle(
            _translate("QtProfileEditor", "Profile Editor")
        )
        self.lbl_bio.setText(_translate("QtProfileEditor", "Bio "))
        self.lbl_parent_id.setText(_translate("QtProfileEditor", "Parent Id "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            _translate("QtProfileEditor", "General"),
        )
        self.lbl_parent.setText(_translate("QtProfileEditor", "Parent "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_relations),
            _translate("QtProfileEditor", "Relations"),
        )
        self.lbl_id.setText(_translate("QtProfileEditor", "Id "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_info),
            _translate("QtProfileEditor", "Info"),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.main_tab,
            self.tab_general,
            self.c_bio,
            self.c_parent_id,
            self.tab_relations,
            self.c_parent,
            self.tab_info,
            self.c_id,
        ]
