# Constants for field types
FIELD_TYPE_BLOB = "blob"
FIELD_TYPE_BOOL = "bool"
FIELD_TYPE_DT = "date-time"
FIELD_TYPE_DATE = "date"
FIELD_TYPE_DURATION = "duration"
FIELD_TYPE_ENUM = "enum"
FIELD_TYPE_FLOAT = "float"
FIELD_TYPE_INTEGER = "integer"
FIELD_TYPE_STRING = "string"
FIELD_TYPE_STRING_LIST = "string-list"
FIELD_TYPE_INT_LIST = "int-list"
FIELD_TYPE_FLOAT_LIST = "float-list"
FIELD_TYPE_FORMATTED = "formatted"
FIELD_TYPE_FILTER = "filter"
FIELD_TYPE_SORT = "sort"
FIELD_TYPE_REF_ONE_TO_MANY = "one-to-many"
FIELD_TYPE_REF_ONE_TO_ONE = "one-to-one"
FIELD_TYPE_REF_MANY_TO_MANY = "many-to-many"
FIELD_TYPE_REF_MANY_TO_ONE = "many-to-one"

# Constants for TypeScript types
TS_TYPE_BYTEBUFFER = "ByteBuffer"
TS_TYPE_BOOLEAN = "boolean"
TS_TYPE_DATE = "Date"
TS_TYPE_NUMBER = "number"
TS_TYPE_STRING = "string"
TS_TYPE_STRING_ARRAY = "string[]"
TS_TYPE_NUMBER_ARRAY = "number[]"
TS_TYPE_SORT = "SortItem[]"
TS_TYPE_ANY_ARRAY = "any[]"

# Constants for Python types
PY_TYPE_BYTES = "bytes"
PY_TYPE_BOOL = "bool"
PY_TYPE_DATE = "Date"
PY_TYPE_DATETIME = "DateTime"
PY_TYPE_TIMEDELTA = "timedelta"
PY_TYPE_STR = "str"
PY_TYPE_FLOAT = "float"
PY_TYPE_INT = "int"
PY_TYPE_STRING_LIST = "list[str]"
PY_TYPE_INT_LIST = "list[int]"
PY_TYPE_FLOAT_LIST = "list[float]"
