from typing import TYPE_CHECKING, Any

from PyQt6 import QtCore, QtGui, QtWidgets

if TYPE_CHECKING:
    from exdrf_qt.controls.filter_dlg.filter_editor import FilterEditor


class Ui_FilterDlg:
    """Autogenerated content.

    Attributes:
        bbox: Bbox.
        c_text: C text.
        horizontalLayout: The layout for the widget.
        verticalLayout: The layout for the widget.

    """

    bbox: "QtWidgets.QDialogButtonBox"
    c_text: "FilterEditor"
    horizontalLayout: "QtWidgets.QHBoxLayout"
    l_btm_and: "QtWidgets.QLabel"
    l_error: "QtWidgets.QLabel"
    l_top_and: "QtWidgets.QLabel"
    verticalLayout: "QtWidgets.QVBoxLayout"
    ctx: "Any"  # Injected by host widget when used as mixin

    def setup_ui(self, FilterDlg):
        from exdrf_qt.controls.filter_dlg.filter_editor import FilterEditor

        FilterDlg.setObjectName("FilterDlg")
        FilterDlg.resize(382, 356)
        self.verticalLayout = QtWidgets.QVBoxLayout(FilterDlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.l_top_and = QtWidgets.QLabel(parent=FilterDlg)
        self.l_top_and.setObjectName("l_top_and")
        self.verticalLayout.addWidget(self.l_top_and)
        self.c_text = FilterEditor(parent=FilterDlg, ctx=self.ctx)
        self.c_text.setObjectName("c_text")
        self.verticalLayout.addWidget(self.c_text)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.l_btm_and = QtWidgets.QLabel(parent=FilterDlg)
        self.l_btm_and.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.l_btm_and.setObjectName("l_btm_and")
        self.horizontalLayout.addWidget(self.l_btm_and)
        self.l_error = QtWidgets.QLabel(parent=FilterDlg)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.l_error.sizePolicy().hasHeightForWidth()
        )
        self.l_error.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 44, 37))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.WindowText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 44, 37))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.WindowText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.WindowText,
            brush,
        )
        self.l_error.setPalette(palette)
        font = QtGui.QFont()
        font.setItalic(True)
        self.l_error.setFont(font)
        self.l_error.setWordWrap(True)
        self.l_error.setObjectName("l_error")
        self.horizontalLayout.addWidget(self.l_error)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.bbox = QtWidgets.QDialogButtonBox(parent=FilterDlg)
        self.bbox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.bbox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Apply
            | QtWidgets.QDialogButtonBox.StandardButton.Cancel
        )
        self.bbox.setObjectName("bbox")
        self.verticalLayout.addWidget(self.bbox)

        self.retranslate_ui(FilterDlg)
        self.bbox.accepted.connect(FilterDlg.accept)  # type: ignore
        self.bbox.rejected.connect(FilterDlg.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FilterDlg)

    def retranslate_ui(self, FilterDlg):
        FilterDlg.setWindowTitle(
            self.ctx.t("gui.filter_dlg.window_title", "Compose Filter")
        )
        self.l_top_and.setText(self.ctx.t("gui.filter_dlg.l_top_and", "AND ("))
        self.l_btm_and.setText(self.ctx.t("gui.filter_dlg.l_btm_and", ")"))
        self.l_error.setText(self.ctx.t("gui.filter_dlg.l_error", "j"))

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.bbox,
            self.c_text,
        ]
