class Ui_QtRelatedItemEditor:
    """Autogenerated content.

    Attributes:
        c_comp_key_owner: C comp key owner.
        c_comp_key_part1: C comp key part1.
        c_comp_key_part2: C comp key part2.
        c_id: C id.
        c_item_data: C item data.
        c_some_int: C some int.
        formLayout: The layout for the widget.
        formLayout1: The layout for the widget.
        formLayout2: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        tab_info: Tab info.
        tab_relations: Tab relations.
        verticalLayout: The layout for the widget.

    """

    c_comp_key_owner: "QCheckBox"
    c_comp_key_part1: "QLineEdit"
    c_comp_key_part2: "QSpinBox"
    c_id: "QSpinBox"
    c_item_data: "QLineEdit"
    c_some_int: "QSpinBox"
    formLayout: "QFormLayout"
    formLayout1: "QFormLayout"
    formLayout2: "QFormLayout"
    lbl_comp_key_owner: "QLabel"
    lbl_comp_key_part1: "QLabel"
    lbl_comp_key_part2: "QLabel"
    lbl_id: "QLabel"
    lbl_item_data: "QLabel"
    lbl_some_int: "QLabel"
    main_tab: "QTabWidget"
    tab_general: "QWidget"
    tab_info: "QWidget"
    tab_relations: "QWidget"
    verticalLayout: "QVBoxLayout"

    def setup_ui(self, QtRelatedItemEditor):

        if not QtRelatedItemEditor.objectName():
            QtRelatedItemEditor.setObjectName("QtRelatedItemEditor")
        QtRelatedItemEditor.resize(480, 640)
        self.verticalLayout = QVBoxLayout(QtRelatedItemEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QTabWidget(QtRelatedItemEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_comp_key_part1 = QLabel(self.tab_general)
        self.lbl_comp_key_part1.setObjectName("lbl_comp_key_part1")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_comp_key_part1
        )

        self.c_comp_key_part1 = QLineEdit(self.tab_general)
        self.c_comp_key_part1.setObjectName("c_comp_key_part1")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.c_comp_key_part1
        )

        self.lbl_comp_key_part2 = QLabel(self.tab_general)
        self.lbl_comp_key_part2.setObjectName("lbl_comp_key_part2")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.LabelRole, self.lbl_comp_key_part2
        )

        self.c_comp_key_part2 = QSpinBox(self.tab_general)
        self.c_comp_key_part2.setObjectName("c_comp_key_part2")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.FieldRole, self.c_comp_key_part2
        )

        self.lbl_item_data = QLabel(self.tab_general)
        self.lbl_item_data.setObjectName("lbl_item_data")

        self.formLayout.setWidget(
            2, QFormLayout.ItemRole.LabelRole, self.lbl_item_data
        )

        self.c_item_data = QLineEdit(self.tab_general)
        self.c_item_data.setObjectName("c_item_data")

        self.formLayout.setWidget(
            2, QFormLayout.ItemRole.FieldRole, self.c_item_data
        )

        self.lbl_some_int = QLabel(self.tab_general)
        self.lbl_some_int.setObjectName("lbl_some_int")

        self.formLayout.setWidget(
            3, QFormLayout.ItemRole.LabelRole, self.lbl_some_int
        )

        self.c_some_int = QSpinBox(self.tab_general)
        self.c_some_int.setObjectName("c_some_int")

        self.formLayout.setWidget(
            3, QFormLayout.ItemRole.FieldRole, self.c_some_int
        )

        self.main_tab.addTab(self.tab_general, "")
        self.tab_relations = QWidget()
        self.tab_relations.setObjectName("tab_relations")
        self.formLayout1 = QFormLayout(self.tab_relations)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_comp_key_owner = QLabel(self.tab_relations)
        self.lbl_comp_key_owner.setObjectName("lbl_comp_key_owner")

        self.formLayout1.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_comp_key_owner
        )

        self.c_comp_key_owner = QCheckBox(self.tab_relations)
        self.c_comp_key_owner.setObjectName("c_comp_key_owner")

        self.formLayout1.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.c_comp_key_owner
        )

        self.main_tab.addTab(self.tab_relations, "")
        self.tab_info = QWidget()
        self.tab_info.setObjectName("tab_info")
        self.formLayout2 = QFormLayout(self.tab_info)
        self.formLayout2.setObjectName("formLayout2")
        self.lbl_id = QLabel(self.tab_info)
        self.lbl_id.setObjectName("lbl_id")

        self.formLayout2.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_id
        )

        self.c_id = QSpinBox(self.tab_info)
        self.c_id.setObjectName("c_id")

        self.formLayout2.setWidget(0, QFormLayout.ItemRole.FieldRole, self.c_id)

        self.main_tab.addTab(self.tab_info, "")

        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtRelatedItemEditor)

        self.main_tab.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(QtRelatedItemEditor)

    # setupUi

    def retranslate_ui(self, QtRelatedItemEditor):
        QtRelatedItemEditor.setWindowTitle(
            QCoreApplication.translate(
                "QtRelatedItemEditor", "RelatedItem Editor", None
            )
        )
        self.lbl_comp_key_part1.setText(
            QCoreApplication.translate(
                "QtRelatedItemEditor", "Comp Key Part1 ", None
            )
        )
        self.lbl_comp_key_part2.setText(
            QCoreApplication.translate(
                "QtRelatedItemEditor", "Comp Key Part2 ", None
            )
        )
        self.lbl_item_data.setText(
            QCoreApplication.translate(
                "QtRelatedItemEditor", "Item Data ", None
            )
        )
        self.lbl_some_int.setText(
            QCoreApplication.translate("QtRelatedItemEditor", "Some Int ", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            QCoreApplication.translate("QtRelatedItemEditor", "General", None),
        )
        self.lbl_comp_key_owner.setText(
            QCoreApplication.translate(
                "QtRelatedItemEditor", "Comp Key Owner ", None
            )
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_relations),
            QCoreApplication.translate(
                "QtRelatedItemEditor", "Relations", None
            ),
        )
        self.lbl_id.setText(
            QCoreApplication.translate("QtRelatedItemEditor", "Id ", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_info),
            QCoreApplication.translate("QtRelatedItemEditor", "Info", None),
        )

    # retranslate_ui

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_comp_key_owner,
            self.c_comp_key_part1,
            self.c_comp_key_part2,
            self.c_id,
            self.c_item_data,
            self.c_some_int,
            self.main_tab,
            self.tab_general,
            self.tab_info,
            self.tab_relations,
        ]
