from PyQt5 import QtCore, QtWidgets


class Ui_QtRelatedItemEditor:
    """Autogenerated content.

    Attributes:
        c_comp_key_owner: C comp key owner.
        c_comp_key_part1: C comp key part1.
        c_comp_key_part2: C comp key part2.
        c_id: C id.
        c_item_data: C item data.
        c_some_int: C some int.
        formLayout: The layout for the widget.
        formLayout1: The layout for the widget.
        formLayout2: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        tab_info: Tab info.
        tab_relations: Tab relations.
        verticalLayout: The layout for the widget.

    """

    c_comp_key_owner: "QtWidgets.QCheckBox"
    c_comp_key_part1: "QtWidgets.QLineEdit"
    c_comp_key_part2: "QtWidgets.QSpinBox"
    c_id: "QtWidgets.QSpinBox"
    c_item_data: "QtWidgets.QLineEdit"
    c_some_int: "QtWidgets.QSpinBox"
    formLayout: "QtWidgets.QFormLayout"
    formLayout1: "QtWidgets.QFormLayout"
    formLayout2: "QtWidgets.QFormLayout"
    lbl_comp_key_owner: "QtWidgets.QLabel"
    lbl_comp_key_part1: "QtWidgets.QLabel"
    lbl_comp_key_part2: "QtWidgets.QLabel"
    lbl_id: "QtWidgets.QLabel"
    lbl_item_data: "QtWidgets.QLabel"
    lbl_some_int: "QtWidgets.QLabel"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    tab_info: "QtWidgets.QWidget"
    tab_relations: "QtWidgets.QWidget"
    verticalLayout: "QtWidgets.QVBoxLayout"

    def setup_ui(self, QtRelatedItemEditor):

        QtRelatedItemEditor.setObjectName("QtRelatedItemEditor")
        QtRelatedItemEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(QtRelatedItemEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(QtRelatedItemEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_comp_key_part1 = QtWidgets.QLabel(self.tab_general)
        self.lbl_comp_key_part1.setObjectName("lbl_comp_key_part1")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_comp_key_part1
        )
        self.c_comp_key_part1 = QtWidgets.QLineEdit(self.tab_general)
        self.c_comp_key_part1.setObjectName("c_comp_key_part1")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_comp_key_part1
        )
        self.lbl_comp_key_part2 = QtWidgets.QLabel(self.tab_general)
        self.lbl_comp_key_part2.setObjectName("lbl_comp_key_part2")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.lbl_comp_key_part2
        )
        self.c_comp_key_part2 = QtWidgets.QSpinBox(self.tab_general)
        self.c_comp_key_part2.setObjectName("c_comp_key_part2")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.c_comp_key_part2
        )
        self.lbl_item_data = QtWidgets.QLabel(self.tab_general)
        self.lbl_item_data.setObjectName("lbl_item_data")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.lbl_item_data
        )
        self.c_item_data = QtWidgets.QLineEdit(self.tab_general)
        self.c_item_data.setObjectName("c_item_data")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.c_item_data
        )
        self.lbl_some_int = QtWidgets.QLabel(self.tab_general)
        self.lbl_some_int.setObjectName("lbl_some_int")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.lbl_some_int
        )
        self.c_some_int = QtWidgets.QSpinBox(self.tab_general)
        self.c_some_int.setObjectName("c_some_int")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.c_some_int
        )
        self.main_tab.addTab(self.tab_general, "")
        self.tab_relations = QtWidgets.QWidget()
        self.tab_relations.setObjectName("tab_relations")
        self.formLayout1 = QtWidgets.QFormLayout(self.tab_relations)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_comp_key_owner = QtWidgets.QLabel(self.tab_relations)
        self.lbl_comp_key_owner.setObjectName("lbl_comp_key_owner")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_comp_key_owner
        )
        self.c_comp_key_owner = QtWidgets.QCheckBox(self.tab_relations)
        self.c_comp_key_owner.setObjectName("c_comp_key_owner")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_comp_key_owner
        )
        self.main_tab.addTab(self.tab_relations, "")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setObjectName("tab_info")
        self.formLayout2 = QtWidgets.QFormLayout(self.tab_info)
        self.formLayout2.setObjectName("formLayout2")
        self.lbl_id = QtWidgets.QLabel(self.tab_info)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_id
        )
        self.c_id = QtWidgets.QSpinBox(self.tab_info)
        self.c_id.setObjectName("c_id")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_id
        )
        self.main_tab.addTab(self.tab_info, "")
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtRelatedItemEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtRelatedItemEditor)

    def retranslate_ui(self, QtRelatedItemEditor):
        _translate = QtCore.QCoreApplication.translate
        QtRelatedItemEditor.setWindowTitle(
            _translate("QtRelatedItemEditor", "RelatedItem Editor")
        )
        self.lbl_comp_key_part1.setText(
            _translate("QtRelatedItemEditor", "Comp Key Part1 ")
        )
        self.lbl_comp_key_part2.setText(
            _translate("QtRelatedItemEditor", "Comp Key Part2 ")
        )
        self.lbl_item_data.setText(
            _translate("QtRelatedItemEditor", "Item Data ")
        )
        self.lbl_some_int.setText(
            _translate("QtRelatedItemEditor", "Some Int ")
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            _translate("QtRelatedItemEditor", "General"),
        )
        self.lbl_comp_key_owner.setText(
            _translate("QtRelatedItemEditor", "Comp Key Owner ")
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_relations),
            _translate("QtRelatedItemEditor", "Relations"),
        )
        self.lbl_id.setText(_translate("QtRelatedItemEditor", "Id "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_info),
            _translate("QtRelatedItemEditor", "Info"),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_comp_key_owner,
            self.c_comp_key_part1,
            self.c_comp_key_part2,
            self.c_id,
            self.c_item_data,
            self.c_some_int,
            self.main_tab,
            self.tab_general,
            self.tab_info,
            self.tab_relations,
        ]
