from typing import TYPE_CHECKING

from PyQt5 import QtCore, QtWidgets

if TYPE_CHECKING:
    from exdrf_qt.controls.seldb.choose_db import ChooseDb


class Ui_TaskRunner:
    """Autogenerated content.

    Attributes:
        lay_main: Lay main.
        c_stacked: C stacked.
        page_1: Page 1.
        lay_page_1: Lay page 1.
        horizontalLayout_2: The layout for the widget.
        c_db_connection: C db connection.
        page_2: Page 2.
        c_progress: C progress.
        lay_button_box: Lay button box.
        c_main_button: C main button.
        c_cancel_button: C cancel button.

    """

    lay_main: "QtWidgets.QVBoxLayout"
    c_stacked: "QtWidgets.QStackedWidget"
    page_1: "QtWidgets.QWidget"
    lay_page_1: "QtWidgets.QVBoxLayout"
    lbl_description: "QtWidgets.QLabel"
    horizontalLayout_2: "QtWidgets.QHBoxLayout"
    lbl_db_connection: "QtWidgets.QLabel"
    c_db_connection: "ChooseDb"
    page_2: "QtWidgets.QWidget"
    c_progress: "QtWidgets.QProgressBar"
    lay_button_box: "QtWidgets.QHBoxLayout"
    c_main_button: "QtWidgets.QPushButton"
    c_cancel_button: "QtWidgets.QPushButton"

    def setup_ui(self, TaskRunner):
        from exdrf_qt.controls.seldb.choose_db import ChooseDb

        TaskRunner.setObjectName("TaskRunner")
        TaskRunner.resize(543, 502)
        self.lay_main = QtWidgets.QVBoxLayout(TaskRunner)
        self.lay_main.setObjectName("lay_main")
        self.c_stacked = QtWidgets.QStackedWidget(TaskRunner)
        self.c_stacked.setObjectName("c_stacked")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.lay_page_1 = QtWidgets.QVBoxLayout(self.page_1)
        self.lay_page_1.setObjectName("lay_page_1")
        self.lbl_description = QtWidgets.QLabel(self.page_1)
        self.lbl_description.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbl_description.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_description.setWordWrap(True)
        self.lbl_description.setTextInteractionFlags(
            QtCore.Qt.LinksAccessibleByMouse
            | QtCore.Qt.TextSelectableByKeyboard
            | QtCore.Qt.TextSelectableByMouse
        )
        self.lbl_description.setObjectName("lbl_description")
        self.lay_page_1.addWidget(self.lbl_description)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint
        )
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_db_connection = QtWidgets.QLabel(self.page_1)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lbl_db_connection.sizePolicy().hasHeightForWidth()
        )
        self.lbl_db_connection.setSizePolicy(sizePolicy)
        self.lbl_db_connection.setObjectName("lbl_db_connection")
        self.horizontalLayout_2.addWidget(self.lbl_db_connection)
        self.c_db_connection = ChooseDb(parent=self.page_1, ctx=self.ctx)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.c_db_connection.sizePolicy().hasHeightForWidth()
        )
        self.c_db_connection.setSizePolicy(sizePolicy)
        self.c_db_connection.setObjectName("c_db_connection")
        self.horizontalLayout_2.addWidget(self.c_db_connection)
        self.lay_page_1.addLayout(self.horizontalLayout_2)
        self.c_stacked.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.c_stacked.addWidget(self.page_2)
        self.lay_main.addWidget(self.c_stacked)
        self.c_progress = QtWidgets.QProgressBar(TaskRunner)
        self.c_progress.setProperty("value", 24)
        self.c_progress.setObjectName("c_progress")
        self.lay_main.addWidget(self.c_progress)
        self.lay_button_box = QtWidgets.QHBoxLayout()
        self.lay_button_box.setObjectName("lay_button_box")
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Minimum,
        )
        self.lay_button_box.addItem(spacerItem)
        self.c_main_button = QtWidgets.QPushButton(TaskRunner)
        self.c_main_button.setObjectName("c_main_button")
        self.lay_button_box.addWidget(self.c_main_button)
        self.c_cancel_button = QtWidgets.QPushButton(TaskRunner)
        self.c_cancel_button.setObjectName("c_cancel_button")
        self.lay_button_box.addWidget(self.c_cancel_button)
        self.lay_main.addLayout(self.lay_button_box)
        self.lbl_db_connection.setBuddy(self.c_db_connection)

        self.retranslate_ui(TaskRunner)
        QtCore.QMetaObject.connectSlotsByName(TaskRunner)

    def retranslate_ui(self, TaskRunner):
        _translate = QtCore.QCoreApplication.translate
        TaskRunner.setWindowTitle(_translate("TaskRunner", "TaskRunner"))
        self.lbl_description.setText(_translate("TaskRunner", "Description"))
        self.lbl_db_connection.setText(
            _translate("TaskRunner", "Database Connection:")
        )
        self.c_main_button.setText(_translate("TaskRunner", "Run"))
        self.c_cancel_button.setText(_translate("TaskRunner", "Cancel"))

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_stacked,
            self.page_1,
            self.c_db_connection,
            self.page_2,
            self.c_progress,
            self.c_main_button,
            self.c_cancel_button,
        ]
