from PyQt5 import QtCore, QtWidgets


class Ui_QtParentEditor:
    """Autogenerated content.

    Attributes:
        verticalLayout: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        formLayout: The layout for the widget.
        c_name: C name.
        c_created_at: C created at.
        c_is_active: C is active.
        tab_relations: Tab relations.
        formLayout1: The layout for the widget.
        c_children: C children.
        c_profile: C profile.
        c_tags: C tags.
        tab_info: Tab info.
        formLayout2: The layout for the widget.
        c_id: C id.

    """

    verticalLayout: "QtWidgets.QVBoxLayout"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    formLayout: "QtWidgets.QFormLayout"
    lbl_name: "QtWidgets.QLabel"
    c_name: "QtWidgets.QLineEdit"
    lbl_created_at: "QtWidgets.QLabel"
    c_created_at: "QtWidgets.QDateTimeEdit"
    lbl_is_active: "QtWidgets.QLabel"
    c_is_active: "QtWidgets.QCheckBox"
    tab_relations: "QtWidgets.QWidget"
    formLayout1: "QtWidgets.QFormLayout"
    lbl_children: "QtWidgets.QLabel"
    c_children: "QtWidgets.QCheckBox"
    lbl_profile: "QtWidgets.QLabel"
    c_profile: "QtWidgets.QCheckBox"
    lbl_tags: "QtWidgets.QLabel"
    c_tags: "QtWidgets.QCheckBox"
    tab_info: "QtWidgets.QWidget"
    formLayout2: "QtWidgets.QFormLayout"
    lbl_id: "QtWidgets.QLabel"
    c_id: "QtWidgets.QSpinBox"

    def setup_ui(self, QtParentEditor):

        QtParentEditor.setObjectName("QtParentEditor")
        QtParentEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(QtParentEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(QtParentEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_name = QtWidgets.QLabel(self.tab_general)
        self.lbl_name.setObjectName("lbl_name")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_name
        )
        self.c_name = QtWidgets.QLineEdit(self.tab_general)
        self.c_name.setObjectName("c_name")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_name
        )
        self.lbl_created_at = QtWidgets.QLabel(self.tab_general)
        self.lbl_created_at.setObjectName("lbl_created_at")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.lbl_created_at
        )
        self.c_created_at = QtWidgets.QDateTimeEdit(self.tab_general)
        self.c_created_at.setObjectName("c_created_at")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.c_created_at
        )
        self.lbl_is_active = QtWidgets.QLabel(self.tab_general)
        self.lbl_is_active.setObjectName("lbl_is_active")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.lbl_is_active
        )
        self.c_is_active = QtWidgets.QCheckBox(self.tab_general)
        self.c_is_active.setObjectName("c_is_active")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.c_is_active
        )
        self.main_tab.addTab(self.tab_general, "")
        self.tab_relations = QtWidgets.QWidget()
        self.tab_relations.setObjectName("tab_relations")
        self.formLayout1 = QtWidgets.QFormLayout(self.tab_relations)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_children = QtWidgets.QLabel(self.tab_relations)
        self.lbl_children.setObjectName("lbl_children")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_children
        )
        self.c_children = QtWidgets.QCheckBox(self.tab_relations)
        self.c_children.setObjectName("c_children")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_children
        )
        self.lbl_profile = QtWidgets.QLabel(self.tab_relations)
        self.lbl_profile.setObjectName("lbl_profile")
        self.formLayout1.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.lbl_profile
        )
        self.c_profile = QtWidgets.QCheckBox(self.tab_relations)
        self.c_profile.setObjectName("c_profile")
        self.formLayout1.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.c_profile
        )
        self.lbl_tags = QtWidgets.QLabel(self.tab_relations)
        self.lbl_tags.setObjectName("lbl_tags")
        self.formLayout1.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.lbl_tags
        )
        self.c_tags = QtWidgets.QCheckBox(self.tab_relations)
        self.c_tags.setObjectName("c_tags")
        self.formLayout1.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.c_tags
        )
        self.main_tab.addTab(self.tab_relations, "")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setObjectName("tab_info")
        self.formLayout2 = QtWidgets.QFormLayout(self.tab_info)
        self.formLayout2.setObjectName("formLayout2")
        self.lbl_id = QtWidgets.QLabel(self.tab_info)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_id
        )
        self.c_id = QtWidgets.QSpinBox(self.tab_info)
        self.c_id.setObjectName("c_id")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_id
        )
        self.main_tab.addTab(self.tab_info, "")
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtParentEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtParentEditor)

    def retranslate_ui(self, QtParentEditor):
        _translate = QtCore.QCoreApplication.translate
        QtParentEditor.setWindowTitle(
            _translate("QtParentEditor", "Parent Editor")
        )
        self.lbl_name.setText(_translate("QtParentEditor", "Name "))
        self.lbl_created_at.setText(_translate("QtParentEditor", "Created At "))
        self.lbl_is_active.setText(_translate("QtParentEditor", "Is Active "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            _translate("QtParentEditor", "General"),
        )
        self.lbl_children.setText(_translate("QtParentEditor", "Children "))
        self.lbl_profile.setText(_translate("QtParentEditor", "Profile "))
        self.lbl_tags.setText(_translate("QtParentEditor", "Tags "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_relations),
            _translate("QtParentEditor", "Relations"),
        )
        self.lbl_id.setText(_translate("QtParentEditor", "Id "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_info),
            _translate("QtParentEditor", "Info"),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.main_tab,
            self.tab_general,
            self.c_name,
            self.c_created_at,
            self.c_is_active,
            self.tab_relations,
            self.c_children,
            self.c_profile,
            self.c_tags,
            self.tab_info,
            self.c_id,
        ]
