from typing import TYPE_CHECKING

from PyQt5 import QtCore, QtWidgets

if TYPE_CHECKING:
    from exdrf_qt.field_ed.api import DrfIntEditor, DrfLineEditor

    from exdrf_dev.qt_gen.db.parents.api import QtParentSiSe


class Ui_QtProfileEditor:
    """Autogenerated content.

    Attributes:
        c_bio: C bio.
        c_id: C id.
        c_parent: C parent.
        formLayout: The layout for the widget.
        formLayout1: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        tab_keys: Tab keys.
        verticalLayout: The layout for the widget.

    """

    c_bio: "DrfLineEditor"
    c_id: "DrfIntEditor"
    c_parent: "QtParentSiSe"
    formLayout: "QtWidgets.QFormLayout"
    formLayout1: "QtWidgets.QFormLayout"
    lbl_bio: "QtWidgets.QLabel"
    lbl_id: "QtWidgets.QLabel"
    lbl_parent: "QtWidgets.QLabel"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    tab_keys: "QtWidgets.QWidget"
    verticalLayout: "QtWidgets.QVBoxLayout"

    def setup_ui(self, QtProfileEditor):
        from exdrf_qt.field_ed.api import DrfIntEditor, DrfLineEditor

        from exdrf_dev.qt_gen.db.parents.api import QtParentSiSe

        QtProfileEditor.setObjectName("QtProfileEditor")
        QtProfileEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(QtProfileEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(QtProfileEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_bio = QtWidgets.QLabel(self.tab_general)
        self.lbl_bio.setObjectName("lbl_bio")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_bio
        )
        self.c_bio = DrfLineEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_bio.setProperty("name", "bio")
        self.c_bio.setProperty("clearable", True)
        self.c_bio.setObjectName("c_bio")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_bio
        )
        self.lbl_parent = QtWidgets.QLabel(self.tab_general)
        self.lbl_parent.setObjectName("lbl_parent")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.lbl_parent
        )
        self.c_parent = QtParentSiSe(parent=self.tab_general, ctx=self.ctx)
        self.c_parent.setProperty("name", "parent")
        self.c_parent.setProperty("clearable", True)
        self.c_parent.setObjectName("c_parent")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.c_parent
        )
        self.main_tab.addTab(self.tab_general, "")
        self.tab_keys = QtWidgets.QWidget()
        self.tab_keys.setObjectName("tab_keys")
        self.formLayout1 = QtWidgets.QFormLayout(self.tab_keys)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_id = QtWidgets.QLabel(self.tab_keys)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_id
        )
        self.c_id = DrfIntEditor(parent=self.tab_keys, ctx=self.ctx)
        self.c_id.setProperty("name", "id")
        self.c_id.setObjectName("c_id")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_id
        )
        self.main_tab.addTab(self.tab_keys, "")
        self.verticalLayout.addWidget(self.main_tab)
        self.lbl_bio.setBuddy(self.c_bio)
        self.lbl_parent.setBuddy(self.c_parent)
        self.lbl_id.setBuddy(self.c_id)

        self.retranslate_ui(QtProfileEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtProfileEditor)

    def retranslate_ui(self, QtProfileEditor):
        _translate = QtCore.QCoreApplication.translate
        QtProfileEditor.setWindowTitle(
            _translate("QtProfileEditor", "Profile Editor")
        )
        self.lbl_bio.setText(_translate("QtProfileEditor", "Bio "))
        self.lbl_parent.setText(_translate("QtProfileEditor", "Parent "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            _translate("QtProfileEditor", "General"),
        )
        self.lbl_id.setText(_translate("QtProfileEditor", "Id "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_keys),
            _translate("QtProfileEditor", "Keys"),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_bio,
            self.c_id,
            self.c_parent,
            self.main_tab,
            self.tab_general,
            self.tab_keys,
        ]
