from typing import TYPE_CHECKING

from PyQt5 import QtCore, QtWidgets

if TYPE_CHECKING:
    from exdrf_qt.field_ed.api import DrfIntEditor, DrfLineEditor, QtParentSiSe


class Ui_QtProfileEditor:
    """Autogenerated content.

    Attributes:
        verticalLayout: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        formLayout: The layout for the widget.
        c_bio: C bio.
        c_id: C id.
        c_parent: C parent.
        c_parent_id: C parent id.

    """

    verticalLayout: "QtWidgets.QVBoxLayout"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    formLayout: "QtWidgets.QFormLayout"
    lbl_bio: "QtWidgets.QLabel"
    c_bio: "DrfLineEditor"
    lbl_id: "QtWidgets.QLabel"
    c_id: "DrfIntEditor"
    lbl_parent: "QtWidgets.QLabel"
    c_parent: "QtParentSiSe"
    lbl_parent_id: "QtWidgets.QLabel"
    c_parent_id: "DrfIntEditor"

    def setup_ui(self, QtProfileEditor):
        from exdrf_qt.field_ed.api import (
            DrfIntEditor,
            DrfLineEditor,
            QtParentSiSe,
        )

        QtProfileEditor.setObjectName("QtProfileEditor")
        QtProfileEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(QtProfileEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(QtProfileEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_bio = QtWidgets.QLabel(self.tab_general)
        self.lbl_bio.setObjectName("lbl_bio")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_bio
        )
        self.c_bio = DrfLineEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_bio.setObjectName("c_bio")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_bio
        )
        self.lbl_id = QtWidgets.QLabel(self.tab_general)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.lbl_id
        )
        self.c_id = DrfIntEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_id.setObjectName("c_id")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.c_id)
        self.lbl_parent = QtWidgets.QLabel(self.tab_general)
        self.lbl_parent.setObjectName("lbl_parent")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.lbl_parent
        )
        self.c_parent = QtParentSiSe(parent=self.tab_general, ctx=self.ctx)
        self.c_parent.setObjectName("c_parent")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.c_parent
        )
        self.lbl_parent_id = QtWidgets.QLabel(self.tab_general)
        self.lbl_parent_id.setObjectName("lbl_parent_id")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.lbl_parent_id
        )
        self.c_parent_id = DrfIntEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_parent_id.setObjectName("c_parent_id")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.c_parent_id
        )
        self.main_tab.addTab(self.tab_general, "")
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtProfileEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtProfileEditor)

    def retranslate_ui(self, QtProfileEditor):
        _translate = QtCore.QCoreApplication.translate
        QtProfileEditor.setWindowTitle(
            _translate("QtProfileEditor", "Profile Editor")
        )
        self.lbl_bio.setText(_translate("QtProfileEditor", "Bio "))
        self.lbl_id.setText(_translate("QtProfileEditor", "Id "))
        self.lbl_parent.setText(_translate("QtProfileEditor", "Parent "))
        self.lbl_parent_id.setText(_translate("QtProfileEditor", "Parent Id "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            _translate("QtProfileEditor", "General"),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.main_tab,
            self.tab_general,
            self.c_bio,
            self.c_id,
            self.c_parent,
            self.c_parent_id,
        ]
