from PyQt5 import QtCore, QtWidgets


class Ui_QtChildEditor:
    """Autogenerated content.

    Attributes:
        verticalLayout: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        formLayout: The layout for the widget.
        c_data: C data.
        c_parent_id: C parent id.
        tab_relations: Tab relations.
        formLayout1: The layout for the widget.
        c_parent: C parent.
        tab_info: Tab info.
        formLayout2: The layout for the widget.
        c_id: C id.

    """

    verticalLayout: "QtWidgets.QVBoxLayout"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    formLayout: "QtWidgets.QFormLayout"
    lbl_data: "QtWidgets.QLabel"
    c_data: "QtWidgets.QLineEdit"
    lbl_parent_id: "QtWidgets.QLabel"
    c_parent_id: "QtWidgets.QSpinBox"
    tab_relations: "QtWidgets.QWidget"
    formLayout1: "QtWidgets.QFormLayout"
    lbl_parent: "QtWidgets.QLabel"
    c_parent: "QtWidgets.QCheckBox"
    tab_info: "QtWidgets.QWidget"
    formLayout2: "QtWidgets.QFormLayout"
    lbl_id: "QtWidgets.QLabel"
    c_id: "QtWidgets.QSpinBox"

    def setup_ui(self, QtChildEditor):

        QtChildEditor.setObjectName("QtChildEditor")
        QtChildEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(QtChildEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(QtChildEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_data = QtWidgets.QLabel(self.tab_general)
        self.lbl_data.setObjectName("lbl_data")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_data
        )
        self.c_data = QtWidgets.QLineEdit(self.tab_general)
        self.c_data.setObjectName("c_data")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_data
        )
        self.lbl_parent_id = QtWidgets.QLabel(self.tab_general)
        self.lbl_parent_id.setObjectName("lbl_parent_id")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.lbl_parent_id
        )
        self.c_parent_id = QtWidgets.QSpinBox(self.tab_general)
        self.c_parent_id.setObjectName("c_parent_id")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.c_parent_id
        )
        self.main_tab.addTab(self.tab_general, "")
        self.tab_relations = QtWidgets.QWidget()
        self.tab_relations.setObjectName("tab_relations")
        self.formLayout1 = QtWidgets.QFormLayout(self.tab_relations)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_parent = QtWidgets.QLabel(self.tab_relations)
        self.lbl_parent.setObjectName("lbl_parent")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_parent
        )
        self.c_parent = QtWidgets.QCheckBox(self.tab_relations)
        self.c_parent.setObjectName("c_parent")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_parent
        )
        self.main_tab.addTab(self.tab_relations, "")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setObjectName("tab_info")
        self.formLayout2 = QtWidgets.QFormLayout(self.tab_info)
        self.formLayout2.setObjectName("formLayout2")
        self.lbl_id = QtWidgets.QLabel(self.tab_info)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_id
        )
        self.c_id = QtWidgets.QSpinBox(self.tab_info)
        self.c_id.setObjectName("c_id")
        self.formLayout2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_id
        )
        self.main_tab.addTab(self.tab_info, "")
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtChildEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtChildEditor)

    def retranslate_ui(self, QtChildEditor):
        _translate = QtCore.QCoreApplication.translate
        QtChildEditor.setWindowTitle(
            _translate("QtChildEditor", "Child Editor")
        )
        self.lbl_data.setText(_translate("QtChildEditor", "Data "))
        self.lbl_parent_id.setText(_translate("QtChildEditor", "Parent Id "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            _translate("QtChildEditor", "General"),
        )
        self.lbl_parent.setText(_translate("QtChildEditor", "Parent "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_relations),
            _translate("QtChildEditor", "Relations"),
        )
        self.lbl_id.setText(_translate("QtChildEditor", "Id "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_info),
            _translate("QtChildEditor", "Info"),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.main_tab,
            self.tab_general,
            self.c_data,
            self.c_parent_id,
            self.tab_relations,
            self.c_parent,
            self.tab_info,
            self.c_id,
        ]
