from typing import TYPE_CHECKING

from PyQt5 import QtCore, QtWidgets

if TYPE_CHECKING:
    from exdrf_qt.field_ed.api import (
        DrfBoolEditor,
        DrfDateTimeEditor,
        DrfLineEditor,
    )

    from exdrf_dev.qt_gen.db.children.api import QtChildMuSe
    from exdrf_dev.qt_gen.db.profiles.api import QtProfileSiSe
    from exdrf_dev.qt_gen.db.tags.api import QtTagMuSe


class Ui_QtParentEditor:
    """Autogenerated content.

    Attributes:
        verticalLayout: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        formLayout: The layout for the widget.
        c_children: C children.
        c_created_at: C created at.
        c_is_active: C is active.
        c_name: C name.
        c_profile: C profile.
        c_tags: C tags.
        tab_keys: Tab keys.
        formLayout1: The layout for the widget.
        c_id: C id.

    """

    verticalLayout: "QtWidgets.QVBoxLayout"
    main_tab: "QtWidgets.QTabWidget"
    tab_general: "QtWidgets.QWidget"
    formLayout: "QtWidgets.QFormLayout"
    lbl_children: "QtWidgets.QLabel"
    c_children: "QtChildMuSe"
    lbl_created_at: "QtWidgets.QLabel"
    c_created_at: "DrfDateTimeEditor"
    lbl_is_active: "QtWidgets.QLabel"
    c_is_active: "DrfBoolEditor"
    lbl_name: "QtWidgets.QLabel"
    c_name: "DrfLineEditor"
    lbl_profile: "QtWidgets.QLabel"
    c_profile: "QtProfileSiSe"
    lbl_tags: "QtWidgets.QLabel"
    c_tags: "QtTagMuSe"
    tab_keys: "QtWidgets.QWidget"
    formLayout1: "QtWidgets.QFormLayout"
    lbl_id: "QtWidgets.QLabel"
    c_id: "QtWidgets.QLineEdit"

    def setup_ui(self, QtParentEditor):
        from exdrf_qt.field_ed.api import (
            DrfBoolEditor,
            DrfDateTimeEditor,
            DrfLineEditor,
        )

        from exdrf_dev.qt_gen.db.children.api import QtChildMuSe
        from exdrf_dev.qt_gen.db.profiles.api import QtProfileSiSe
        from exdrf_dev.qt_gen.db.tags.api import QtTagMuSe

        QtParentEditor.setObjectName("QtParentEditor")
        QtParentEditor.resize(480, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(QtParentEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QtWidgets.QTabWidget(QtParentEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QtWidgets.QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QtWidgets.QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_children = QtWidgets.QLabel(self.tab_general)
        self.lbl_children.setObjectName("lbl_children")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_children
        )
        self.c_children = QtChildMuSe(parent=self.tab_general, ctx=self.ctx)
        self.c_children.setProperty("name", "children")
        self.c_children.setObjectName("c_children")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_children
        )
        self.lbl_created_at = QtWidgets.QLabel(self.tab_general)
        self.lbl_created_at.setObjectName("lbl_created_at")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.lbl_created_at
        )
        self.c_created_at = DrfDateTimeEditor(
            parent=self.tab_general, ctx=self.ctx
        )
        self.c_created_at.setProperty("name", "created_at")
        self.c_created_at.setObjectName("c_created_at")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.c_created_at
        )
        self.lbl_is_active = QtWidgets.QLabel(self.tab_general)
        self.lbl_is_active.setObjectName("lbl_is_active")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.lbl_is_active
        )
        self.c_is_active = DrfBoolEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_is_active.setProperty("name", "is_active")
        self.c_is_active.setObjectName("c_is_active")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.c_is_active
        )
        self.lbl_name = QtWidgets.QLabel(self.tab_general)
        self.lbl_name.setObjectName("lbl_name")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.lbl_name
        )
        self.c_name = DrfLineEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_name.setProperty("name", "name")
        self.c_name.setObjectName("c_name")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.c_name
        )
        self.lbl_profile = QtWidgets.QLabel(self.tab_general)
        self.lbl_profile.setObjectName("lbl_profile")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.lbl_profile
        )
        self.c_profile = QtProfileSiSe(parent=self.tab_general, ctx=self.ctx)
        self.c_profile.setProperty("name", "profile")
        self.c_profile.setObjectName("c_profile")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.FieldRole, self.c_profile
        )
        self.lbl_tags = QtWidgets.QLabel(self.tab_general)
        self.lbl_tags.setObjectName("lbl_tags")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.LabelRole, self.lbl_tags
        )
        self.c_tags = QtTagMuSe(parent=self.tab_general, ctx=self.ctx)
        self.c_tags.setProperty("name", "tags")
        self.c_tags.setObjectName("c_tags")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.FieldRole, self.c_tags
        )
        self.main_tab.addTab(self.tab_general, "")
        self.tab_keys = QtWidgets.QWidget()
        self.tab_keys.setObjectName("tab_keys")
        self.formLayout1 = QtWidgets.QFormLayout(self.tab_keys)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_id = QtWidgets.QLabel(self.tab_keys)
        self.lbl_id.setObjectName("lbl_id")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.lbl_id
        )
        self.c_id = QtWidgets.QLineEdit(self.tab_keys)
        self.c_id.setReadOnly(True)
        self.c_id.setObjectName("c_id")
        self.formLayout1.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.c_id
        )
        self.main_tab.addTab(self.tab_keys, "")
        self.verticalLayout.addWidget(self.main_tab)

        self.retranslate_ui(QtParentEditor)
        self.main_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QtParentEditor)

    def retranslate_ui(self, QtParentEditor):
        _translate = QtCore.QCoreApplication.translate
        QtParentEditor.setWindowTitle(
            _translate("QtParentEditor", "Parent Editor")
        )
        self.lbl_children.setText(_translate("QtParentEditor", "Children "))
        self.lbl_created_at.setText(_translate("QtParentEditor", "Created At "))
        self.lbl_is_active.setText(_translate("QtParentEditor", "Is Active "))
        self.lbl_name.setText(_translate("QtParentEditor", "Name "))
        self.lbl_profile.setText(_translate("QtParentEditor", "Profile "))
        self.lbl_tags.setText(_translate("QtParentEditor", "Tags "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            _translate("QtParentEditor", "General"),
        )
        self.lbl_id.setText(_translate("QtParentEditor", "Id "))
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_keys),
            _translate("QtParentEditor", "Keys"),
        )

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.main_tab,
            self.tab_general,
            self.c_children,
            self.c_created_at,
            self.c_is_active,
            self.c_name,
            self.c_profile,
            self.c_tags,
            self.tab_keys,
            self.c_id,
        ]
