from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from exdrf_qt.field_ed.api import (
        DrfBoolEditor,
        DrfDateTimeEditor,
        DrfIntEditor,
        DrfLineEditor,
        QtParentRelTag,
    )

    from exdrf_dev.qt_gen.db.children.api import QtChildMuSe
    from exdrf_dev.qt_gen.db.profiles.api import QtProfileSiSe


class Ui_QtParentEditor:
    """Autogenerated content.

    Attributes:
        c_children: C children.
        c_created_at: C created at.
        c_id: C id.
        c_is_active: C is active.
        c_name: C name.
        c_profile: C profile.
        c_tags: C tags.
        formLayout: The layout for the widget.
        formLayout1: The layout for the widget.
        formLayout2: The layout for the widget.
        main_tab: Main tab.
        tab_general: Tab general.
        tab_keys: Tab keys.
        tab_tags_rel: Tab tags rel.
        verticalLayout: The layout for the widget.

    """

    c_children: "QtChildMuSe"
    c_created_at: "DrfDateTimeEditor"
    c_id: "DrfIntEditor"
    c_is_active: "DrfBoolEditor"
    c_name: "DrfLineEditor"
    c_profile: "QtProfileSiSe"
    c_tags: "QtParentRelTag"
    formLayout: "QFormLayout"
    formLayout1: "QFormLayout"
    formLayout2: "QVBoxLayout"
    lbl_children: "QLabel"
    lbl_created_at: "QLabel"
    lbl_id: "QLabel"
    lbl_is_active: "QLabel"
    lbl_name: "QLabel"
    lbl_profile: "QLabel"
    main_tab: "QTabWidget"
    tab_general: "QWidget"
    tab_keys: "QWidget"
    tab_tags_rel: "QWidget"
    verticalLayout: "QVBoxLayout"

    def setup_ui(self, QtParentEditor):
        from exdrf_qt.field_ed.api import (
            DrfBoolEditor,
            DrfDateTimeEditor,
            DrfIntEditor,
            DrfLineEditor,
            QtParentRelTag,
        )

        from exdrf_dev.qt_gen.db.children.api import QtChildMuSe
        from exdrf_dev.qt_gen.db.profiles.api import QtProfileSiSe

        if not QtParentEditor.objectName():
            QtParentEditor.setObjectName("QtParentEditor")
        QtParentEditor.resize(480, 640)
        self.verticalLayout = QVBoxLayout(QtParentEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_tab = QTabWidget(QtParentEditor)
        self.main_tab.setObjectName("main_tab")
        self.tab_general = QWidget()
        self.tab_general.setObjectName("tab_general")
        self.formLayout = QFormLayout(self.tab_general)
        self.formLayout.setObjectName("formLayout")
        self.lbl_name = QLabel(self.tab_general)
        self.lbl_name.setObjectName("lbl_name")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_name
        )

        self.c_name = DrfLineEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_name.setObjectName("c_name")
        self.c_name.setProperty("name", "name")

        self.formLayout.setWidget(
            0, QFormLayout.ItemRole.FieldRole, self.c_name
        )

        self.lbl_created_at = QLabel(self.tab_general)
        self.lbl_created_at.setObjectName("lbl_created_at")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.LabelRole, self.lbl_created_at
        )

        self.c_created_at = DrfDateTimeEditor(
            parent=self.tab_general, ctx=self.ctx
        )
        self.c_created_at.setObjectName("c_created_at")
        self.c_created_at.setProperty("name", "created_at")

        self.formLayout.setWidget(
            1, QFormLayout.ItemRole.FieldRole, self.c_created_at
        )

        self.lbl_is_active = QLabel(self.tab_general)
        self.lbl_is_active.setObjectName("lbl_is_active")

        self.formLayout.setWidget(
            2, QFormLayout.ItemRole.LabelRole, self.lbl_is_active
        )

        self.c_is_active = DrfBoolEditor(parent=self.tab_general, ctx=self.ctx)
        self.c_is_active.setObjectName("c_is_active")
        self.c_is_active.setProperty("name", "is_active")

        self.formLayout.setWidget(
            2, QFormLayout.ItemRole.FieldRole, self.c_is_active
        )

        self.lbl_profile = QLabel(self.tab_general)
        self.lbl_profile.setObjectName("lbl_profile")

        self.formLayout.setWidget(
            3, QFormLayout.ItemRole.LabelRole, self.lbl_profile
        )

        self.c_profile = QtProfileSiSe(parent=self.tab_general, ctx=self.ctx)
        self.c_profile.setObjectName("c_profile")
        self.c_profile.setProperty("name", "profile")
        self.c_profile.setProperty("clearable", True)

        self.formLayout.setWidget(
            3, QFormLayout.ItemRole.FieldRole, self.c_profile
        )

        self.lbl_children = QLabel(self.tab_general)
        self.lbl_children.setObjectName("lbl_children")

        self.formLayout.setWidget(
            4, QFormLayout.ItemRole.LabelRole, self.lbl_children
        )

        self.c_children = QtChildMuSe(parent=self.tab_general, ctx=self.ctx)
        self.c_children.setObjectName("c_children")
        self.c_children.setProperty("name", "children")
        self.c_children.setProperty("clearable", True)

        self.formLayout.setWidget(
            4, QFormLayout.ItemRole.FieldRole, self.c_children
        )

        self.main_tab.addTab(self.tab_general, "")
        self.tab_keys = QWidget()
        self.tab_keys.setObjectName("tab_keys")
        self.formLayout1 = QFormLayout(self.tab_keys)
        self.formLayout1.setObjectName("formLayout1")
        self.lbl_id = QLabel(self.tab_keys)
        self.lbl_id.setObjectName("lbl_id")

        self.formLayout1.setWidget(
            0, QFormLayout.ItemRole.LabelRole, self.lbl_id
        )

        self.c_id = DrfIntEditor(parent=self.tab_keys, ctx=self.ctx)
        self.c_id.setObjectName("c_id")
        self.c_id.setProperty("name", "id")

        self.formLayout1.setWidget(0, QFormLayout.ItemRole.FieldRole, self.c_id)

        self.main_tab.addTab(self.tab_keys, "")
        self.tab_tags_rel = QWidget()
        self.tab_tags_rel.setObjectName("tab_tags_rel")
        self.formLayout2 = QVBoxLayout(self.tab_tags_rel)
        self.formLayout2.setObjectName("formLayout2")
        self.c_tags = QtParentRelTag(parent=self.tab_tags_rel, ctx=self.ctx)
        self.c_tags.setObjectName("c_tags")
        self.c_tags.setProperty("name", "tags")

        self.formLayout2.addWidget(self.c_tags)

        self.main_tab.addTab(self.tab_tags_rel, "")

        self.verticalLayout.addWidget(self.main_tab)

        self.lbl_name.setBuddy(self.c_name)
        self.lbl_created_at.setBuddy(self.c_created_at)
        self.lbl_is_active.setBuddy(self.c_is_active)
        self.lbl_profile.setBuddy(self.c_profile)
        self.lbl_children.setBuddy(self.c_children)
        self.lbl_id.setBuddy(self.c_id)

        self.retranslate_ui(QtParentEditor)

        self.main_tab.setCurrentIndex(0)

        QMetaObject.connectSlotsByName(QtParentEditor)

    # setupUi

    def retranslate_ui(self, QtParentEditor):
        QtParentEditor.setWindowTitle(
            QCoreApplication.translate("QtParentEditor", "Parent Editor", None)
        )
        self.lbl_name.setText(
            QCoreApplication.translate("QtParentEditor", "Name ", None)
        )
        self.lbl_created_at.setText(
            QCoreApplication.translate("QtParentEditor", "Created At ", None)
        )
        self.lbl_is_active.setText(
            QCoreApplication.translate("QtParentEditor", "Is Active ", None)
        )
        self.lbl_profile.setText(
            QCoreApplication.translate("QtParentEditor", "Profile ", None)
        )
        self.lbl_children.setText(
            QCoreApplication.translate("QtParentEditor", "Children ", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_general),
            QCoreApplication.translate("QtParentEditor", "General", None),
        )
        self.lbl_id.setText(
            QCoreApplication.translate("QtParentEditor", "Id ", None)
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_keys),
            QCoreApplication.translate("QtParentEditor", "Keys", None),
        )
        self.main_tab.setTabText(
            self.main_tab.indexOf(self.tab_tags_rel),
            QCoreApplication.translate("QtParentEditor", "Tags", None),
        )

    # retranslate_ui

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_children,
            self.c_created_at,
            self.c_id,
            self.c_is_active,
            self.c_name,
            self.c_profile,
            self.c_tags,
            self.main_tab,
            self.tab_general,
            self.tab_keys,
            self.tab_tags_rel,
        ]
