from typing import Any

from PyQt6 import QtCore, QtWidgets


class Ui_ColumnSelDlg:
    """Autogenerated content.

    Attributes:
        bbox: Bbox.
        c_available: C available.
        c_splitter: C splitter.
        c_visible: C visible.
        lay_available: Lay available.
        lay_visible: Lay visible.
        verticalLayout_3: The layout for the widget.
        widget: Widget.
        widget1: Widget1.

    """

    bbox: "QtWidgets.QDialogButtonBox"
    c_available: "QtWidgets.QListWidget"
    c_available_label: "QtWidgets.QLabel"
    c_splitter: "QtWidgets.QSplitter"
    c_visible: "QtWidgets.QListWidget"
    c_visible_label: "QtWidgets.QLabel"
    lay_available: "QtWidgets.QVBoxLayout"
    lay_visible: "QtWidgets.QVBoxLayout"
    verticalLayout_3: "QtWidgets.QVBoxLayout"
    widget: "QtWidgets.QWidget"
    widget1: "QtWidgets.QWidget"
    ctx: "Any"  # Injected by host widget when used as mixin

    def setup_ui(self, ColumnSelDlg):

        ColumnSelDlg.setObjectName("ColumnSelDlg")
        ColumnSelDlg.resize(439, 389)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ColumnSelDlg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.c_splitter = QtWidgets.QSplitter(parent=ColumnSelDlg)
        self.c_splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.c_splitter.setObjectName("c_splitter")
        self.widget = QtWidgets.QWidget(parent=self.c_splitter)
        self.widget.setObjectName("widget")
        self.lay_available = QtWidgets.QVBoxLayout(self.widget)
        self.lay_available.setContentsMargins(0, 0, 0, 0)
        self.lay_available.setObjectName("lay_available")
        self.c_available_label = QtWidgets.QLabel(parent=self.widget)
        self.c_available_label.setObjectName("c_available_label")
        self.lay_available.addWidget(self.c_available_label)
        self.c_available = QtWidgets.QListWidget(parent=self.widget)
        self.c_available.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.c_available.setDragEnabled(True)
        self.c_available.setDragDropMode(
            QtWidgets.QAbstractItemView.DragDropMode.DragDrop
        )
        self.c_available.setDefaultDropAction(QtCore.Qt.DropAction.MoveAction)
        self.c_available.setAlternatingRowColors(True)
        self.c_available.setMovement(QtWidgets.QListView.Movement.Free)
        self.c_available.setObjectName("c_available")
        self.lay_available.addWidget(self.c_available)
        self.widget1 = QtWidgets.QWidget(parent=self.c_splitter)
        self.widget1.setObjectName("widget1")
        self.lay_visible = QtWidgets.QVBoxLayout(self.widget1)
        self.lay_visible.setContentsMargins(0, 0, 0, 0)
        self.lay_visible.setObjectName("lay_visible")
        self.c_visible_label = QtWidgets.QLabel(parent=self.widget1)
        self.c_visible_label.setObjectName("c_visible_label")
        self.lay_visible.addWidget(self.c_visible_label)
        self.c_visible = QtWidgets.QListWidget(parent=self.widget1)
        self.c_visible.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.c_visible.setDragEnabled(True)
        self.c_visible.setDragDropMode(
            QtWidgets.QAbstractItemView.DragDropMode.DragDrop
        )
        self.c_visible.setDefaultDropAction(QtCore.Qt.DropAction.MoveAction)
        self.c_visible.setAlternatingRowColors(True)
        self.c_visible.setMovement(QtWidgets.QListView.Movement.Free)
        self.c_visible.setObjectName("c_visible")
        self.lay_visible.addWidget(self.c_visible)
        self.verticalLayout_3.addWidget(self.c_splitter)
        self.bbox = QtWidgets.QDialogButtonBox(parent=ColumnSelDlg)
        self.bbox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.bbox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Apply
            | QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Reset
        )
        self.bbox.setObjectName("bbox")
        self.verticalLayout_3.addWidget(self.bbox)

        self.retranslate_ui(ColumnSelDlg)
        self.bbox.accepted.connect(ColumnSelDlg.accept)  # type: ignore
        self.bbox.rejected.connect(ColumnSelDlg.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ColumnSelDlg)

    def retranslate_ui(self, ColumnSelDlg):
        ColumnSelDlg.setWindowTitle(
            self.ctx.t("gui.column_sel_dlg.window_title", "Columns Editor")
        )
        self.c_available_label.setText(
            self.ctx.t("gui.column_sel_dlg.c_available_label", "Available")
        )
        self.c_available.setSortingEnabled(False)
        self.c_visible_label.setText(
            self.ctx.t("gui.column_sel_dlg.c_visible_label", "Visible")
        )
        self.c_visible.setSortingEnabled(False)

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.bbox,
            self.c_available,
            self.c_splitter,
            self.c_visible,
            self.widget,
            self.widget1,
        ]
