class Ui_ColumnSelDlg:
    """Autogenerated content.

    Attributes:
        bbox: Bbox.
        c_available: C available.
        c_splitter: C splitter.
        c_visible: C visible.
        lay_available: Lay available.
        lay_visible: Lay visible.
        verticalLayout_3: The layout for the widget.
        widget: Widget.
        widget1: Widget1.

    """

    bbox: "QDialogButtonBox"
    c_available: "QListWidget"
    c_available_label: "QLabel"
    c_splitter: "QSplitter"
    c_visible: "QListWidget"
    c_visible_label: "QLabel"
    lay_available: "QVBoxLayout"
    lay_visible: "QVBoxLayout"
    verticalLayout_3: "QVBoxLayout"
    widget: "QWidget"
    widget1: "QWidget"

    def setup_ui(self, ColumnSelDlg):

        if not ColumnSelDlg.objectName():
            ColumnSelDlg.setObjectName("ColumnSelDlg")
        ColumnSelDlg.resize(439, 389)
        self.verticalLayout_3 = QVBoxLayout(ColumnSelDlg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.c_splitter = QSplitter(ColumnSelDlg)
        self.c_splitter.setObjectName("c_splitter")
        self.c_splitter.setOrientation(Qt.Horizontal)
        self.widget = QWidget(self.c_splitter)
        self.widget.setObjectName("widget")
        self.lay_available = QVBoxLayout(self.widget)
        self.lay_available.setObjectName("lay_available")
        self.lay_available.setContentsMargins(0, 0, 0, 0)
        self.c_available_label = QLabel(self.widget)
        self.c_available_label.setObjectName("c_available_label")

        self.lay_available.addWidget(self.c_available_label)

        self.c_available = QListWidget(self.widget)
        self.c_available.setObjectName("c_available")
        self.c_available.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.c_available.setDragEnabled(True)
        self.c_available.setDragDropMode(QAbstractItemView.DragDrop)
        self.c_available.setDefaultDropAction(Qt.MoveAction)
        self.c_available.setAlternatingRowColors(True)
        self.c_available.setMovement(QListView.Free)
        self.c_available.setSortingEnabled(False)

        self.lay_available.addWidget(self.c_available)

        self.c_splitter.addWidget(self.widget)
        self.widget1 = QWidget(self.c_splitter)
        self.widget1.setObjectName("widget1")
        self.lay_visible = QVBoxLayout(self.widget1)
        self.lay_visible.setObjectName("lay_visible")
        self.lay_visible.setContentsMargins(0, 0, 0, 0)
        self.c_visible_label = QLabel(self.widget1)
        self.c_visible_label.setObjectName("c_visible_label")

        self.lay_visible.addWidget(self.c_visible_label)

        self.c_visible = QListWidget(self.widget1)
        self.c_visible.setObjectName("c_visible")
        self.c_visible.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.c_visible.setDragEnabled(True)
        self.c_visible.setDragDropMode(QAbstractItemView.DragDrop)
        self.c_visible.setDefaultDropAction(Qt.MoveAction)
        self.c_visible.setAlternatingRowColors(True)
        self.c_visible.setMovement(QListView.Free)
        self.c_visible.setSortingEnabled(False)

        self.lay_visible.addWidget(self.c_visible)

        self.c_splitter.addWidget(self.widget1)

        self.verticalLayout_3.addWidget(self.c_splitter)

        self.bbox = QDialogButtonBox(ColumnSelDlg)
        self.bbox.setObjectName("bbox")
        self.bbox.setOrientation(Qt.Horizontal)
        self.bbox.setStandardButtons(
            QDialogButtonBox.Apply
            | QDialogButtonBox.Cancel
            | QDialogButtonBox.Reset
        )

        self.verticalLayout_3.addWidget(self.bbox)

        self.retranslate_ui(ColumnSelDlg)
        self.bbox.accepted.connect(ColumnSelDlg.accept)
        self.bbox.rejected.connect(ColumnSelDlg.reject)

        QMetaObject.connectSlotsByName(ColumnSelDlg)

    # setupUi

    def retranslate_ui(self, ColumnSelDlg):
        ColumnSelDlg.setWindowTitle(
            QCoreApplication.translate("ColumnSelDlg", "Columns Editor", None)
        )
        self.c_available_label.setText(
            QCoreApplication.translate("ColumnSelDlg", "Available", None)
        )
        self.c_visible_label.setText(
            QCoreApplication.translate("ColumnSelDlg", "Visible", None)
        )

    # retranslate_ui

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.bbox,
            self.c_available,
            self.c_splitter,
            self.c_visible,
            self.widget,
            self.widget1,
        ]
