from PyQt5 import QtCore, QtWidgets


class Ui_ColumnSelDlg:
    """Autogenerated content.

    Attributes:
        verticalLayout_3: The layout for the widget.
        c_splitter: C splitter.
        widget: Widget.
        lay_available: Lay available.
        c_available: C available.
        widget1: Widget1.
        lay_visible: Lay visible.
        c_visible: C visible.
        bbox: Bbox.

    """

    verticalLayout_3: "QtWidgets.QVBoxLayout"
    c_splitter: "QtWidgets.QSplitter"
    widget: "QtWidgets.QWidget"
    lay_available: "QtWidgets.QVBoxLayout"
    c_available_label: "QtWidgets.QLabel"
    c_available: "QtWidgets.QListWidget"
    widget1: "QtWidgets.QWidget"
    lay_visible: "QtWidgets.QVBoxLayout"
    c_visible_label: "QtWidgets.QLabel"
    c_visible: "QtWidgets.QListWidget"
    bbox: "QtWidgets.QDialogButtonBox"

    def setup_ui(self, ColumnSelDlg):

        ColumnSelDlg.setObjectName("ColumnSelDlg")
        ColumnSelDlg.resize(439, 389)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ColumnSelDlg)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.c_splitter = QtWidgets.QSplitter(ColumnSelDlg)
        self.c_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.c_splitter.setObjectName("c_splitter")
        self.widget = QtWidgets.QWidget(self.c_splitter)
        self.widget.setObjectName("widget")
        self.lay_available = QtWidgets.QVBoxLayout(self.widget)
        self.lay_available.setContentsMargins(0, 0, 0, 0)
        self.lay_available.setObjectName("lay_available")
        self.c_available_label = QtWidgets.QLabel(self.widget)
        self.c_available_label.setObjectName("c_available_label")
        self.lay_available.addWidget(self.c_available_label)
        self.c_available = QtWidgets.QListWidget(self.widget)
        self.c_available.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers
        )
        self.c_available.setDragEnabled(True)
        self.c_available.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.c_available.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.c_available.setAlternatingRowColors(True)
        self.c_available.setMovement(QtWidgets.QListView.Free)
        self.c_available.setObjectName("c_available")
        self.lay_available.addWidget(self.c_available)
        self.widget1 = QtWidgets.QWidget(self.c_splitter)
        self.widget1.setObjectName("widget1")
        self.lay_visible = QtWidgets.QVBoxLayout(self.widget1)
        self.lay_visible.setContentsMargins(0, 0, 0, 0)
        self.lay_visible.setObjectName("lay_visible")
        self.c_visible_label = QtWidgets.QLabel(self.widget1)
        self.c_visible_label.setObjectName("c_visible_label")
        self.lay_visible.addWidget(self.c_visible_label)
        self.c_visible = QtWidgets.QListWidget(self.widget1)
        self.c_visible.setEditTriggers(
            QtWidgets.QAbstractItemView.NoEditTriggers
        )
        self.c_visible.setDragEnabled(True)
        self.c_visible.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.c_visible.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.c_visible.setAlternatingRowColors(True)
        self.c_visible.setMovement(QtWidgets.QListView.Free)
        self.c_visible.setObjectName("c_visible")
        self.lay_visible.addWidget(self.c_visible)
        self.verticalLayout_3.addWidget(self.c_splitter)
        self.bbox = QtWidgets.QDialogButtonBox(ColumnSelDlg)
        self.bbox.setOrientation(QtCore.Qt.Horizontal)
        self.bbox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Apply
            | QtWidgets.QDialogButtonBox.Cancel
            | QtWidgets.QDialogButtonBox.Reset
        )
        self.bbox.setObjectName("bbox")
        self.verticalLayout_3.addWidget(self.bbox)

        self.retranslate_ui(ColumnSelDlg)
        self.bbox.accepted.connect(ColumnSelDlg.accept)  # type: ignore
        self.bbox.rejected.connect(ColumnSelDlg.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ColumnSelDlg)

    def retranslate_ui(self, ColumnSelDlg):
        _translate = QtCore.QCoreApplication.translate
        ColumnSelDlg.setWindowTitle(
            _translate("ColumnSelDlg", "Columns Editor")
        )
        self.c_available_label.setText(_translate("ColumnSelDlg", "Available"))
        self.c_available.setSortingEnabled(False)
        self.c_visible_label.setText(_translate("ColumnSelDlg", "Visible"))
        self.c_visible.setSortingEnabled(False)

    def enum_controls(self):
        """Enumerate the controls in the form."""
        return [
            self.c_splitter,
            self.widget,
            self.c_available,
            self.widget1,
            self.c_visible,
            self.bbox,
        ]
